#!/bin/sh

cat << EOF
global {
	DENY_LOGIN="no"
	PORT="$BFTPD_PORT"
	PASSIVE_PORTS="$BFTPD_PASSIVE_PORTS"
	DATAPORT20="no"
	ADMIN_PASS="x"
	PATH_BFTPDUTMP="/var/run/bftpd/bftpdutmp"
	XFER_BUFSIZE="2048"
	ALLOW_FXP="no"
	CONTROL_TIMEOUT="300"
	DATA_TIMEOUT="30"
	RATIO="none"
	ROOTDIR="%h"
	UMASK="022"
	LOGFILE="/var/log/bftpd.log"
	HELLO_STRING="bftpd %v at %i ready."
	AUTO_CHDIR="/"
	AUTH="PASSWD"
	RESOLVE_CLIENT_IP="no"
	MOTD_GLOBAL="/etc/motd"
	MOTD_USER="/.ftpmotd"
	RESOLVE_UIDS="yes"
	DO_CHROOT="yes"
	LOG_WTMP="yes"
	BIND_TO_ADDR="any"
	PATH_FTPUSERS="/mod/etc/ftpusers"
	AUTH_ETCSHELLS="no"
	ALLOWCOMMAND_DELE="yes"
	ALLOWCOMMAND_STOR="yes"
	ALLOWCOMMAND_SITE="yes"
	HIDE_GROUP=""
	QUIT_MSG="See you later ..."
	USERLIMIT_GLOBAL="0"
	USERLIMIT_SINGLEUSER="0"
}
user ftp {
	ANONYMOUS_USER="$BFTPD_ANONYMOUS"
	DENY_LOGIN="no"
	ROOTDIR="/home/ftp"
}
user anonymous {
	ALIAS="ftp"
}
user root {
	DENY_LOGIN="Root login not allowed."
}
EOF
