#!/var/tmp/sh

# Load answering machine settings
#  $1= Account-ID
load_am_settings() {

	ACC_ID="$1"

	AM_ACTIVE="$GLOBAL_AM_ACTIVE"
	AM_PIN="$GLOBAL_AM_PIN"
	AM_MENU="$GLOBAL_AM_MENU"
	AM_BEEP="$GLOBAL_AM_BEEP"
	AM_HOOKUP_TYPE="$GLOBAL_AM_HOOKUP_TYPE"
	AM_RECORD_TYPE="$GLOBAL_AM_RECORD_TYPE"
	AM_ANNOUNCEMENT_START="$GLOBAL_AM_ANNOUNCEMENT_START"
	AM_ANNOUNCEMENT_END="$GLOBAL_AM_ANNOUNCEMENT_END"
	AM_RING_TIME="$GLOBAL_AM_RING_TIME"
	AM_RECORD_TIME="$GLOBAL_AM_RECORD_TIME"
	AM_SCHEDULE_START="$GLOBAL_AM_SCHEDULE_START"
	AM_SCHEDULE_END="$GLOBAL_AM_SCHEDULE_END"
	AM_MAIL="$GLOBAL_AM_MAIL"
	AM_MAIL_TO="$GLOBAL_AM_MAIL_TO"
	AM_MAIL_FROM="$GLOBAL_AM_MAIL_FROM"
	AM_MAIL_SERVER="$GLOBAL_AM_MAIL_SERVER"
	AM_MAIL_USERNAME="$GLOBAL_AM_MAIL_USERNAME"
	AM_MAIL_PASSWORD="$GLOBAL_AM_MAIL_PASSWORD"
	AM_MAIL_DELETE_AFTER_SEND="$GLOBAL_AM_MAIL_DELETE_AFTER_SEND"
	AM_FTP="$GLOBAL_AM_FTP"
	AM_FTP_SERVER="$GLOBAL_AM_FTP_SERVER"
	AM_FTP_PORT="$GLOBAL_AM_FTP_PORT"
	AM_FTP_PATH="$GLOBAL_AM_FTP_PATH"
	AM_FTP_USERNAME="$GLOBAL_AM_FTP_USERNAME"
	AM_FTP_PASSWORD="$GLOBAL_AM_FTP_PASSWORD"

	eval ACC_AM_ACTIVE="\$ACC${ACC_ID}_AM_ACTIVE"
	if [ "$ACC_AM_ACTIVE" = "0" ];
	then
	  AM_ACTIVE="0"
	fi

	if [ "$ACC_AM_ACTIVE" = "1" ];
	then
	  AM_ACTIVE="1"
	  eval ACC_AM_PIN="\$ACC${ACC_ID}_AM_PIN"
	  eval ACC_AM_MENU="\$ACC${ACC_ID}_AM_MENU"
	  eval ACC_AM_BEEP="\$ACC${ACC_ID}_AM_BEEP"
	  eval ACC_AM_HOOKUP_TYPE="\$ACC${ACC_ID}_AM_HOOKUP_TYPE"
	  eval ACC_AM_RECORD_TYPE="\$ACC${ACC_ID}_AM_RECORD_TYPE"
	  eval ACC_AM_ANNOUNCEMENT_START="\$ACC${ACC_ID}_AM_ANNOUNCEMENT_START"
	  eval ACC_AM_ANNOUNCEMENT_END="\$ACC${ACC_ID}_AM_ANNOUNCEMENT_END"
	  eval ACC_AM_RING_TIME="\$ACC${ACC_ID}_AM_RING_TIME"
	  eval ACC_AM_RECORD_TIME="\$ACC${ACC_ID}_AM_RECORD_TIME"
	  eval ACC_AM_SCHEDULE_START="\$ACC${ACC_ID}_AM_SCHEDULE_START"
	  eval ACC_AM_SCHEDULE_END="\$ACC${ACC_ID}_AM_SCHEDULE_END"
	  eval ACC_AM_MAIL="\$ACC${ACC_ID}_AM_MAIL"
	  eval ACC_AM_MAIL_TO="\$ACC${ACC_ID}_AM_MAIL_TO"
	  eval ACC_AM_MAIL_FROM="\$ACC${ACC_ID}_AM_MAIL_FROM"
	  eval ACC_AM_MAIL_SERVER="\$ACC${ACC_ID}_AM_MAIL_SERVER"
	  eval ACC_AM_MAIL_USERNAME="\$ACC${ACC_ID}_AM_MAIL_USERNAME"
	  eval ACC_AM_MAIL_PASSWORD="\$ACC${ACC_ID}_AM_MAIL_PASSWORD"
	  eval ACC_AM_MAIL_DELETE_AFTER_SEND="\$ACC${ACC_ID}_AM_MAIL_DELETE_AFTER_SEND"
	  eval ACC_AM_FTP="\$ACC${ACC_ID}_AM_FTP"
	  eval ACC_AM_FTP_SERVER="\$ACC${ACC_ID}_AM_FTP_SERVER"
	  eval ACC_AM_FTP_PORT="\$ACC${ACC_ID}_AM_FTP_PORT"
	  eval ACC_AM_FTP_PATH="\$ACC${ACC_ID}_AM_FTP_PATH"
	  eval ACC_AM_FTP_USERNAME="\$ACC${ACC_ID}_AM_FTP_USERNAME"
	  eval ACC_AM_FTP_PASSWORD="\$ACC${ACC_ID}_AM_FTP_PASSWORD"
	  if [ "$ACC_AM_PIN" != "" ]; then AM_PIN="$ACC_AM_PIN"; fi
	  if [ "$ACC_AM_MENU" != "" ]; then AM_MENU="$ACC_AM_MENU"; fi
	  if [ "$ACC_AM_BEEP" != "" ]; then AM_BEEP="$ACC_AM_BEEP"; fi
	  if [ "$ACC_AM_HOOKUP_TYPE" != "" ]; then AM_HOOKUP_TYPE="$ACC_AM_HOOKUP_TYPE"; fi
	  if [ "$ACC_AM_RECORD_TYPE" != "" ]; then AM_RECORD_TYPE="$ACC_AM_RECORD_TYPE"; fi
	  if [ "$ACC_AM_ANNOUNCEMENT_START" != "" ]; then AM_ANNOUNCEMENT_START="$ACC_AM_ANNOUNCEMENT_START"; fi
	  if [ "$ACC_AM_ANNOUNCEMENT_END" != "" ]; then AM_ANNOUNCEMENT_END"$ACC_AM_ANNOUNCEMENT_END"; fi
	  if [ "$ACC_AM_RING_TIME" != "" ]; then AM_RING_TIME="$ACC_AM_RING_TIME"; fi
	  if [ "$ACC_AM_RECORD_TIME" != "" ]; then AM_RECORD_TIME="$ACC_AM_RECORD_TIME"; fi
	  if [ "$ACC_AM_SCHEDULE_START" != "" ]; then AM_SCHEDULE_START="$ACC_AM_SCHEDULE_START"; fi
	  if [ "$ACC_AM_SCHEDULE_END" != "" ]; then AM_SCHEDULE_END="$ACC_AM_SCHEDULE_END"; fi
	  if [ "$ACC_AM_MAIL" != "" ]; then AM_MAIL="$ACC_AM_MAIL"; fi
	  if [ "$ACC_AM_MAIL_FROM" != "" ]; then AM_MAIL_FROM="$ACC_AM_MAIL_FROM"; fi
	  if [ "$ACC_AM_MAIL_TO" != "" ]; then AM_MAIL_TO="$ACC_AM_MAIL_TO"; fi
	  if [ "$ACC_AM_MAIL_SERVER" != "" ]; then AM_MAIL_SERVER="$ACC_AM_MAIL_SERVER"; fi
	  if [ "$ACC_AM_MAIL_USERNAME" != "" ]; then AM_MAIL_USERNAME="$ACC_AM_MAIL_USERNAME"; fi
	  if [ "$ACC_AM_MAIL_PASSWORD" != "" ]; then AM_MAIL_PASSWORD="$ACC_AM_MAIL_PASSWORD"; fi
	  if [ "$ACC_AM_MAIL_DELETE_AFTER_SEND" != "" ]; then AM_MAIL_DELETE_AFTER_SEND="$ACC_AM_MAIL_DELETE_AFTER_SEND"; fi
	  if [ "$ACC_AM_FTP" != "" ]; then AM_FTP="$ACC_AM_FTP"; fi
	  if [ "$ACC_AM_FTP_SERVER" != "" ]; then AM_FTP_SERVER="$ACC_AM_FTP_SERVER"; fi
	  if [ "$ACC_AM_FTP_PORT" != "" ]; then AM_FTP_PORT="$ACC_AM_FTP_PORT"; fi
	  if [ "$ACC_AM_FTP_PATH" != "" ]; then AM_FTP_PATH="$ACC_AM_FTP_PATH"; fi
	  if [ "$ACC_AM_FTP_USERNAME" != "" ]; then AM_FTP_USERNAME="$ACC_AM_FTP_USERNAME"; fi
	  if [ "$ACC_AM_FTP_PASSWORD" != "" ]; then AM_FTP_PASSWORD="$ACC_AM_FTP_PASSWORD"; fi
	fi
}
