$(call PKG_INIT_BIN, 1.1.7)
$(PKG)_SOURCE:=Imaging-$($(PKG)_VERSION).tar.gz
$(PKG)_HASH:=895bc7c2498c8e1f9b99938f1a40dc86b3f149741f105cf7c7bd2e0725405211
$(PKG)_SITE:=http://effbot.org/downloads

$(PKG)_TARGET_BINARY:=$($(PKG)_DEST_DIR)$(PYTHON_SITE_PKG_DIR)/PIL/_imaging.so

$(PKG)_DEPENDS_ON += python freetype jpeg zlib

$(PKG)_REBUILD_SUBOPTS += FREETZ_PACKAGE_PYTHON_STATIC

$(PKG_SOURCE_DOWNLOAD)
$(PKG_UNPACKED)
$(PKG_CONFIGURED_NOP)

$($(PKG)_TARGET_BINARY): $($(PKG)_DIR)/.configured
	$(call Build/PyMod/PKG, PYTHON_IMAGING_LIBRARY, , TARGET_ARCH_BE="$(TARGET_ARCH_BE)")
	$(RM) -r $(PYTHON_IMAGING_LIBRARY_DEST_DIR)/usr/bin
	(cd $(PYTHON_IMAGING_LIBRARY_DEST_DIR)$(PYTHON_SITE_PKG_DIR); mv PIL/PIL-*.egg-info .;)

$(pkg):

$(pkg)-precompiled: $($(PKG)_TARGET_BINARY)

$(pkg)-clean:
	$(RM) -r $(PYTHON_IMAGING_LIBRARY_DIR)/build

$(pkg)-uninstall:
	$(RM) -r \
		$(PYTHON_IMAGING_LIBRARY_DEST_DIR)$(PYTHON_SITE_PKG_DIR)/PIL \
		$(PYTHON_IMAGING_LIBRARY_DEST_DIR)$(PYTHON_SITE_PKG_DIR)/PIL.pth \
		$(PYTHON_IMAGING_LIBRARY_DEST_DIR)$(PYTHON_SITE_PKG_DIR)/PIL-*.egg-info

$(PKG_FINISH)
