#!/bin/sh

[ "$(/etc/init.d/rc.openntpd status)" == "stopped" ] && exit 0

if [ "$1" = "online" ]; then
	logger -t info Restart NTPD due to online status change
	(sleep 5; /etc/init.d/rc.openntpd reload)&
fi
