#!/bin/bash
# generates docs/patches/README.md
MDPWD="$(dirname $(realpath $0))"
INPWD="$MDPWD/../../config/ui"

SYMS=$(
for sym in $(sed -n 's/^[ \t]*\(menu\)*config FREETZ_//p' "$INPWD/patches.in"); do
	[ "$sym" != "${sym#REMOVE_}" ] && cat="000Removal patches" || cat="Other patches"
	echo "$cat##$sym"
done | sort )

echo '[//]: # ( Do not edit this file! Run generate.sh to create it. )' > "$MDPWD/README.md"
echo -n "Content: " >> "$MDPWD/README.md"
echo "$SYMS" | sed 's/##.*//g' | uniq | sed 's/^000//' | while read cat; do echo -n "[$cat](#$(echo ${cat,,} | sed 's/ /-/g')) - "; done | sed 's/...$//' >> "$MDPWD/README.md"
echo "$SYMS" | sed 's/##.*//g' | uniq | while read cat; do
	echo -e "\n# ${cat//0}"
	[ -z "$CTN" ] && CTN="Index: " && for x in $(echo {A..Z}); do CTN="$CTN[$x](#${x,,}) - "; done && echo ${CTN:0:-3}
	echo "$SYMS" | sed -n "s/^${cat}##//p" | while read sym; do
		[ "${cat:0:3}" == "000" ] && [ "${sym:7:1}" != "$IDX" ] && IDX="${sym:7:1}" && echo -e "\n### ${IDX^^}"
		TMP="$(grep -P "^[ \t]*(menu)*config FREETZ_$sym( .*|$)" "$INPWD/patches.in" -A80 -m1)"

		dsc="$(echo "$TMP" | grep -P '^[ \t]*$' -m1 -B80 | sed -rn 's/[ \t]*(bool|string) "([^\"]*)"[ \t]*.*/\2/p' | head -n1)"
		[ -z "$dsc" ] && echo "ignored: $sym" 1>&2 && continue
		[ "${dsc// /_}" != "$(echo ${dsc// /_} | sed "s/^$sym//I")" ] && itm="$dsc" || itm="$sym: $dsc"

		if [ -e "$MDPWD/$sym.md" ]; then
			sed "1c# $dsc" -i "$MDPWD/$sym.md"
			itm="[$itm]($sym.md)"
		else
			itm="<u>$itm</u>"
		fi
		anc="${sym//_/-}"
		echo -e "\n  * **$itm<a id='${anc,,}'></a>**<br>"

		L="$(echo "$TMP" | grep -P '^[ \t]*$' -m1 -B80 | grep -P '^[ \t]*help[ \t]*$' -nm1 | sed 's/:.*//')"
		C="$(echo "$TMP" | wc -l | sed 's/ .*//')"
		[ -z "$L" -o -z "$C" ] && echo "nohelp1: $sym" 1>&2 && continue
		T=$(( $C - $L))
		N="$(echo "$TMP" | tail -n "$T" | grep -P "^[ \t]*(#|(end)*if|config|bool|string|int|depends on|(end)*menu|comment|menuconfig|(end)*choice|prompt|select|default|source|help)($|\t| )" -n | head -n1 | sed 's/:.*//')"
		help="$(echo "$TMP" | tail -n "$T" | head -n "$(( ${N:-99} - 1 ))" | grep -vP '^[ \t]*$' | sed 's/[ \t]*$//g;s/^[ \t]*//g;s/$/ /g' | tr -d '\n' | sed 's/ $//')"
		[ -z "$help" ] && echo "nohelp2: $sym" 1>&2 && continue
		echo "    $help"

	done
done >> "$MDPWD/README.md"

