MKLIBS_HOST_VERSION:=0.1.34
MKLIBS_HOST_SOURCE:=mklibs_$(MKLIBS_HOST_VERSION).tar.gz
MKLIBS_HOST_SOURCE_MD5:=afe0ed527ba96b8a882b5de350603007
MKLIBS_HOST_SITE:=http://archive.debian.org/debian/pool/main/m/mklibs
MKLIBS_HOST_DIR:=$(TOOLS_SOURCE_DIR)/mklibs-$(MKLIBS_HOST_VERSION)
MKLIBS_HOST_MAKE_DIR:=$(TOOLS_DIR)/make/mklibs-host
MKLIBS_HOST_DESTDIR:=$(FREETZ_BASE_DIR)/$(TOOLS_DIR)/build/bin
MKLIBS_HOST_SCRIPT:=$(MKLIBS_HOST_DIR)/src/mklibs
MKLIBS_HOST_TARGET_SCRIPT:=$(MKLIBS_HOST_DESTDIR)/mklibs
MKLIBS_HOST_READELF_BINARY:=$(MKLIBS_HOST_DIR)/src/mklibs-readelf/mklibs-readelf
MKLIBS_HOST_READELF_TARGET_BINARY:=$(MKLIBS_HOST_DESTDIR)/mklibs-readelf


mklibs-host-source: $(DL_DIR)/$(MKLIBS_HOST_SOURCE)
$(DL_DIR)/$(MKLIBS_HOST_SOURCE): | $(DL_DIR)
	$(DL_TOOL) $(DL_DIR) $(MKLIBS_HOST_SOURCE) $(MKLIBS_HOST_SITE) $(MKLIBS_HOST_SOURCE_MD5)

mklibs-host-unpacked: $(MKLIBS_HOST_DIR)/.unpacked
$(MKLIBS_HOST_DIR)/.unpacked: $(DL_DIR)/$(MKLIBS_HOST_SOURCE) | $(TOOLS_SOURCE_DIR) $(UNPACK_TARBALL_PREREQUISITES)
	$(call UNPACK_TARBALL,$(DL_DIR)/$(MKLIBS_HOST_SOURCE),$(TOOLS_SOURCE_DIR))
	$(call APPLY_PATCHES,$(MKLIBS_HOST_MAKE_DIR)/patches,$(MKLIBS_HOST_DIR))
	touch $@

$(MKLIBS_HOST_SCRIPT): $(MKLIBS_HOST_DIR)/.unpacked

$(MKLIBS_HOST_DIR)/.configured: $(MKLIBS_HOST_DIR)/.unpacked
	(cd $(MKLIBS_HOST_DIR); $(RM) config.cache; \
		./configure \
		--prefix=/ \
		$(DISABLE_NLS) \
		$(SILENT) \
	);
	touch $@

$(MKLIBS_HOST_READELF_BINARY): $(MKLIBS_HOST_DIR)/.configured
	$(MAKE) CC="$(TOOLS_CC)" CXX="$(TOOLS_CXX)" CFLAGS="$(TOOLS_CFLAGS)" LDFLAGS="$(TOOLS_LDFLAGS)" -C $(MKLIBS_HOST_DIR) all $(SILENT)

$(MKLIBS_HOST_TARGET_SCRIPT): $(MKLIBS_HOST_SCRIPT)
	$(INSTALL_FILE)

$(MKLIBS_HOST_READELF_TARGET_BINARY): $(MKLIBS_HOST_READELF_BINARY)
	$(INSTALL_FILE)

mklibs-host-precompiled: $(MKLIBS_HOST_TARGET_SCRIPT) $(MKLIBS_HOST_READELF_TARGET_BINARY)


mklibs-host-clean:
	-$(MAKE) -C $(MKLIBS_HOST_DIR) clean

mklibs-host-dirclean:
	$(RM) -r $(MKLIBS_HOST_DIR)

mklibs-host-distclean: mklibs-host-dirclean
	$(RM) -r $(MKLIBS_HOST_TARGET_SCRIPT) $(MKLIBS_HOST_READELF_TARGET_BINARY)

