#!/bin/bash
# generates patches/README.md
MYPWD="$(dirname $(realpath $0))"

SYMS=$(
for sym in $(sed -n 's/^[ \t]*config FREETZ_//p' "$MYPWD/../config/ui/patches.in"); do
[ "$sym" != "${sym#REMOVE_}" ] && cat="000Removal patches" || cat="Other patches"
echo "$cat##$sym"
done | sort )

echo '[//]: # ( Do not edit this file! Run generate.sh to create it. )' > "$MYPWD/README.md"
echo "$SYMS" | sed 's/##.*//g' | uniq | while read cat; do
echo -e "\n### ${cat//0}"
echo "$SYMS" | sed -n "s/^${cat}##//p" | while read sym; do
TMP="$(grep -P "^[ \t]*config FREETZ_$sym( .*|$)" "$MYPWD/../config/ui/patches.in" -A80 -m1)"

dsc="$(echo "$TMP" | grep -P '^[ \t]*$' -m1 -B80 | sed -rn 's/[ \t]*(bool|string) "([^\"]*)"[ \t]*.*/\2/p' | head -n1)"
[ -z "$dsc" ] && echo "ignored: $sym" 1>&2 && continue
[ "${dsc// /_}" != "$(echo ${dsc// /_} | sed "s/^$sym//I")" ] && itm="$dsc" || itm="$sym: $dsc"

[ -e "$MYPWD/../docs/wiki/patches/${sym,,}.html" ] && lnk="https://freetz-ng.github.io/freetz-ng/wiki/patches/${sym,,}" || lnk=""
[ -e "$MYPWD/README/$sym.md" ] && lnk="README/$sym.md"
[ -n "$lnk" ] && itm="[$itm]($lnk)" || itm="<u>$itm</u>"

echo -e "\n  * **$itm<a id='${sym,,}'></a>**<br>"

L="$(echo "$TMP" | grep -P '^[ \t]*$' -m1 -B80 | grep -P '^[ \t]*help[ \t]*$' -nm1 | sed 's/:.*//')"
C="$(echo "$TMP" | wc -l | sed 's/ .*//')"
[ -z "$L" -o -z "$C" ] && echo "nohelp1: $sym" 1>&2 && continue
T=$(( $C - $L))
N="$(echo "$TMP" | tail -n "$T" | grep -P "^[ \t]*(#|(end)*if|config|bool|string|int|depends on|(end)*menu|comment|menuconfig|(end)*choice|prompt|select|default|source|help)" -n | head -n1 | sed 's/:.*//')"
help="$(echo "$TMP" | tail -n "$T" | head -n "$(( $N - 1 ))" | grep -vP '^[ \t]*$' | sed 's/[ \t]*$//g;s/^[ \t]*//g;s/$/ /g' | tr -d '\n' | sed 's/ $//')"
[ -z "$help" ] && echo "nohelp2: $sym" 1>&2 && continue
echo "    $help"

done
done >> "$MYPWD/README.md"

