#!/bin/bash

# Custom firmware modifications

# Directories:
#  ./firmware	- untared firmware
#  ./filesystem	- unpacked filesystem squashfs
#  ./kernel	- unpacked kernel & hidden kernel squashfs

all() {
	dummy=0
}

all_no_freetz() {
	dummy=0

	# restore telnet support, the user still needs to activate it via the phone code (#96*7*)
#	ln -sf ../../bin/busybox ./filesystem/usr/sbin/telnetd

	# source freetz-helper-functions and freetz .config
	# only necessary if freetz patch-scripts are used for modifications
#	. "$(dirname $0)"/tools/freetz_functions
#	. "$(dirname $0)"/tools/freetz_patch
#	. "$(dirname $0)"/.config

	# enforce urlader settings, useful on boxes with bootloader version >=1.3179 (7490) resp. >=1.3229 (7580)
#	. ../../patches/scripts/101-enforce_urlader-settings.sh

	# restore debug.cfg support (using Freetz script)
#	. ../../patches/scripts/114-debug_cfg_support.sh

	# patch away / hide "vom Hersteller nicht unterstützte Änderungen"
#	. ../../patches/scripts/195-patch_webmenu_signed.sh

	# restore volume counter support, 7412 only (using Freetz script)
#	. ../../patches/scripts/241-restore_vol_counter.sh

	# add modfs boot-manager (using Freetz script)
#	. ../../patches/scripts/800-modfs_boot_manager.sh
}

clean() {
	dummy=0
}

case "$1" in
	""|all)
		all
		;;
	all_no_freetz)
		all_no_freetz
		;;
	clean)
		clean
		;;
	*)
		echo "Usage: $0 {all|clean}" 1>&2
		exit 1
		;;
esac

exit 0
