$(call TOOLS_INIT, 4.3)
$(PKG)_SOURCE:=squashfs$($(PKG)_VERSION).tar.gz
$(PKG)_SOURCE_MD5:=d92ab59aabf5173f2a59089531e30dbf
$(PKG)_SITE:=@SF/squashfs

# Enable legacy SquashFS formats support (SquashFS-1/2/3, ZLIB/LZMA1 compressed)
# 1 - to enable
# 0 - to disable
$(PKG)_ENABLE_LEGACY_FORMATS_SUPPORT:=1

$(PKG)_BUILD_DIR:=$($(PKG)_DIR)/squashfs-tools

$(PKG)_TOOLS:=mksquashfs unsquashfs
$(PKG)_TOOLS_BUILD_DIR:=$(addprefix $($(PKG)_BUILD_DIR)/,$($(PKG)_TOOLS))
$(PKG)_TOOLS_TARGET_DIR:=$($(PKG)_TOOLS:%=$(TOOLS_DIR)/%4-avm-be)


$(pkg)-source: $(DL_DIR)/$($(PKG)_SOURCE)
#
$(DL_DIR)/$($(PKG)_SOURCE): | $(DL_DIR)
	$(DL_TOOL) $(DL_DIR) $(SQUASHFS4_BE_HOST_SOURCE) $(SQUASHFS4_BE_HOST_SITE) $(SQUASHFS4_BE_HOST_SOURCE_MD5)
#

$(pkg)-unpacked: $($(PKG)_DIR)/.unpacked
$($(PKG)_DIR)/.unpacked: $(DL_DIR)/$($(PKG)_SOURCE) | $(TOOLS_SOURCE_DIR) $(UNPACK_TARBALL_PREREQUISITES)
	mkdir -p $(SQUASHFS4_BE_HOST_DIR)
	$(call UNPACK_TARBALL,$(DL_DIR)/$(SQUASHFS4_BE_HOST_SOURCE),$(SQUASHFS4_BE_HOST_DIR),1)
	$(call APPLY_PATCHES,$(SQUASHFS4_BE_HOST_MAKE_DIR)/patches,$(SQUASHFS4_BE_HOST_DIR))
	touch $@

$($(PKG)_TOOLS_BUILD_DIR): $($(PKG)_DIR)/.unpacked $(LZMA2_HOST_DIR)/liblzma.a
	$(TOOLS_SUBMAKE) -C $(SQUASHFS4_BE_HOST_BUILD_DIR) \
		CC="$(TOOLS_CC)" \
		CXX="$(TOOLS_CXX)" \
		EXTRA_CFLAGS="-fcommon -DTARGET_FORMAT=AVM_BE" \
		EXTRA_LDFLAGS="" \
		LEGACY_FORMATS_SUPPORT=$(SQUASHFS4_BE_HOST_ENABLE_LEGACY_FORMATS_SUPPORT) \
		GZIP_SUPPORT=$(SQUASHFS4_BE_HOST_ENABLE_LEGACY_FORMATS_SUPPORT) \
		LZMA_XZ_SUPPORT=$(SQUASHFS4_BE_HOST_ENABLE_LEGACY_FORMATS_SUPPORT) \
		XZ_SUPPORT=1 \
		XZ_DIR="$(abspath $(LZMA2_HOST_DIR))" \
		COMP_DEFAULT=xz \
		XATTR_SUPPORT=0 \
		XATTR_DEFAULT=0 \
		$(SQUASHFS4_BE_HOST_TOOLS)
	touch -c $@

$($(PKG)_TOOLS_TARGET_DIR): $(TOOLS_DIR)/%4-avm-be: $($(PKG)_BUILD_DIR)/%
	$(INSTALL_FILE)

$(pkg)-precompiled: $($(PKG)_TOOLS_TARGET_DIR)


$(pkg)-clean:
	-$(MAKE) -C $(SQUASHFS4_BE_HOST_BUILD_DIR) clean

$(pkg)-dirclean:
	$(RM) -r $(SQUASHFS4_BE_HOST_DIR)

$(pkg)-distclean: $(pkg)-dirclean
	$(RM) $(SQUASHFS4_BE_HOST_TOOLS_TARGET_DIR)

$(TOOLS_FINISH)
