$(call PKG_INIT_BIN, 0.4.0)
DTMFBOX_SOURCE:=dtmfbox-$(DTMFBOX_VERSION)-src.tar.gz
DTMFBOX_SITE:=http://fritz.v3v.de/dtmfbox/dtmfbox-src
DTMFBOX_DIR:=$(SOURCE_DIR)/dtmfbox-$(DTMFBOX_VERSION)-src
DTMFBOX_BINARY:=$(DTMFBOX_DIR)/dtmfbox
DTMFBOX_PKG_VERSION:=0.1
DTMFBOX_PKG_SITE:=http://fritz.v3v.de/dtmfbox/package
DTMFBOX_PKG_SOURCE:=dtmfbox-$(DTMFBOX_VERSION)-dsmod-$(DTMFBOX_PKG_VERSION).tar.gz
DTMFBOX_TARGET_BINARY:=$(DTMFBOX_TARGET_DIR)/root/usr/sbin/dtmfbox
$(PKG)_STARTLEVEL=40

DTMFBOX_CFLAGS:=-DDTMFBOX_WIN32=0 
DTMFBOX_CFLAGS+=-DDTMFBOX_USE_SOUND=0
DTMFBOX_CFLAGS+=-DDTMFBOX_USE_CAPI=$(if $(DS_PACKAGE_DTMFBOX_WITH_CAPI),1,0)
DTMFBOX_CFLAGS+=-DDTMFBOX_USE_VOIP=$(if $(DS_PACKAGE_DTMFBOX_WITH_VOIP),1,0)
DTMFBOX_CFLAGS+=-DDTMFBOX_USE_ICE=$(if $(DS_PACKAGE_DTMFBOX_WITH_ICE),1,0)
DTMFBOX_CFLAGS+=-DDTMFBOX_HELP_USAGE=$(if $(DS_PACKAGE_DTMFBOX_WITH_HELPUSAGE),1,0)
DTMFBOX_CFLAGS+=-DDTMFBOX_RESAMPLE_QUALITY=$(DS_PACKAGE_DTMFBOX_RESAMPLE_QUALITY)
DTMFBOX_CFLAGS+=-DPJMEDIA_HAS_G711_CODEC=1
DTMFBOX_CFLAGS+=-DPJMEDIA_HAS_ILBC_CODEC=0 
DTMFBOX_CFLAGS+=-DPJMEDIA_HAS_GSM_CODEC=0
DTMFBOX_CFLAGS+=-DPJMEDIA_HAS_L16_CODEC=0
DTMFBOX_CFLAGS+=-DPJ_LOG_MAX_LEVEL=$(DS_PACKAGE_DTMFBOX_LOGLEVEL)
DTMFBOX_LDLIBS:=-lpjsip-ua -lpjsip-simple -lpjsip -lpjmedia-codec -lpjmedia -lpjnath -lpjlib-util -lpj -lresample

$(PKG)_DEPENDS_ON := libcapi pjproject

$(PKG)_CONFIG_SUBOPTS += DS_PACKAGE_$(PKG)_WITH_CAPI
$(PKG)_CONFIG_SUBOPTS += DS_PACKAGE_$(PKG)_WITH_VOIP
$(PKG)_CONFIG_SUBOPTS += DS_PACKAGE_$(PKG)_WITH_ICE
$(PKG)_CONFIG_SUBOPTS += DS_PACKAGE_$(PKG)_WITH_HELPUSAGE

$(PKG_SOURCE_DOWNLOAD)

$(DL_DIR)/$(DTMFBOX_PKG_SOURCE): | $(DL_DIR)
	@$(DL_TOOL) $(DL_DIR) $(TOPDIR)/.config $(DTMFBOX_PKG_SOURCE) $(DTMFBOX_PKG_SITE)

$(PKG_UNPACKED)

$(DTMFBOX_DIR)/.configured: $(DTMFBOX_DIR)/.unpacked
	for i in $(DTMFBOX_MAKE_DIR)/patches/*.patch; do \
		$(PATCH_TOOL) $(DTMFBOX_DIR) $$i; \
	done
	cp $(DTMFBOX_DIR)/Makefile.mipsel $(DTMFBOX_DIR)/Makefile
	touch $@

$(DTMFBOX_BINARY): $(DTMFBOX_DIR)/.configured
	PATH="$(TARGET_PATH)" \
		$(TARGET_CONFIGURE_OPTS) \
		CFLAGS="$(TARGET_CFLAGS) $(DTMFBOX_CFLAGS)" \
		LDLIBS="$(DTMFBOX_LDLIBS)" \
		$(MAKE) -C $(DTMFBOX_DIR) all 

$(DTMFBOX_TARGET_BINARY): $(DTMFBOX_BINARY)
	$(INSTALL_BINARY_STRIP)

$(PACKAGES_DIR)/.dtmfbox-$(DTMFBOX_VERSION): $(DL_DIR)/$(DTMFBOX_PKG_SOURCE) | $(PACKAGES_DIR)
	@tar -C $(PACKAGES_DIR) -xzf $(DL_DIR)/$(DTMFBOX_PKG_SOURCE)
	@touch $@

dtmfbox: $(PACKAGES_DIR)/.dtmfbox-$(DTMFBOX_VERSION)

dtmfbox-package: $(PACKAGES_DIR)/.dtmfbox-$(DTMFBOX_VERSION)
	tar -C $(PACKAGES_DIR) $(VERBOSE) --exclude .svn -czf $(PACKAGES_BUILD_DIR)/$(DTMFBOX_PKG_SOURCE) dtmfbox-$(DTMFBOX_VERSION)

dtmfbox-precompiled: $(DTMFBOX_TARGET_BINARY)

dtmfbox-clean:
	-$(MAKE) -C $(DTMFBOX_DIR) clean
	rm -f $(PACKAGES_BUILD_DIR)/$(DTMFBOX_PKG_SOURCE)

dtmfbox-uninstall:
	rm -f $(DTMFBOX_TARGET_BINARY)

$(PKG_FINISH)
