#!/bin/sh
#
# script to correct strange default route by dsld
#

#- important variables
#$1={online|offline]
#DNS1=
#DNS2=
#IPADDR=
#GATEWAY=

#- debug
#	exec 1> "/tmp/$(basename "$0").log"
#	exec 2>&1
#	echo "`date` -- $(basename "$0") $*"
#	env | sort
#	set -x

#- magic
case "$1" in
	online )
		DEFAULTROUTEIF="`route -n | awk '/^0.0.0.0[[:space:]]+0.0.0.0/ {print $8}'`"
		if [ "$DEFAULTROUTEIF" = "dsl" ]; then
			ifconfig $DEFAULTROUTEIF $IPADDR dstaddr $IPADDR
			ifconfig $DEFAULTROUTEIF:dsld 169.254.2.1 dstaddr 169.254.2.1
			DEFAULTROUTEIF_IPADDR="$IPADDR"
			route del default 2> /dev/null
			route add default gw $DEFAULTROUTEIF_IPADDR dev $DEFAULTROUTEIF
		fi
	;;
esac
