#!/bin/sh
DAEMON=onlinechanged-cgi
[ ! -f /tmp/flash/$DAEMON ] && exit 0

case "$1" in
	online|offline)
		logger -t ONLINECHANGED "Executing ONLINECHANGED-CGI ($1)"
		sh /tmp/flash/$DAEMON $1
		;;
esac
