BUSYBOX_HOST_VERSION:=1.34.1
BUSYBOX_HOST_SOURCE:=busybox-$(BUSYBOX_HOST_VERSION).tar.bz2
BUSYBOX_HOST_SOURCE_SHA256:=415fbd89e5344c96acf449d94a6f956dbed62e18e835fc83e064db33a34bd549
BUSYBOX_HOST_SITE:=https://www.busybox.net/downloads

BUSYBOX_HOST_MAKE_DIR:=$(TOOLS_DIR)/make/busybox-host
BUSYBOX_HOST_DIR:=$(TOOLS_SOURCE_DIR)/busybox-$(BUSYBOX_HOST_VERSION)
BUSYBOX_HOST_BINARY:=$(BUSYBOX_HOST_DIR)/busybox
BUSYBOX_HOST_CONFIG_FILE:=$(BUSYBOX_HOST_MAKE_DIR)/Config.busybox
BUSYBOX_HOST_TARGET_DIR:=$(TOOLS_DIR)
BUSYBOX_HOST_TARGET_BINARY:=$(TOOLS_DIR)/busybox


busybox-host-source: $(DL_DIR)/$(BUSYBOX_HOST_SOURCE)
$(DL_DIR)/$(BUSYBOX_HOST_SOURCE): | $(DL_DIR)
	$(DL_TOOL) $(DL_DIR) $(BUSYBOX_HOST_SOURCE) $(BUSYBOX_HOST_SITE) $(BUSYBOX_HOST_SOURCE_SHA256)

busybox-host-unpacked: $(BUSYBOX_HOST_DIR)/.unpacked
$(BUSYBOX_HOST_DIR)/.unpacked: $(DL_DIR)/$(BUSYBOX_HOST_SOURCE) | $(TOOLS_SOURCE_DIR) tar-host
	$(TAR) -C $(TOOLS_SOURCE_DIR) $(VERBOSE) -xf $(DL_DIR)/$(BUSYBOX_HOST_SOURCE)
	$(call APPLY_PATCHES,$(BUSYBOX_HOST_MAKE_DIR)/patches,$(BUSYBOX_HOST_DIR))
	touch $@

$(BUSYBOX_HOST_DIR)/.configured: $(BUSYBOX_HOST_DIR)/.unpacked $(BUSYBOX_HOST_CONFIG_FILE)
	cp $(BUSYBOX_HOST_CONFIG_FILE) $(BUSYBOX_HOST_DIR)/.config
	$(TOOL_SUBMAKE) -C $(BUSYBOX_HOST_DIR) oldconfig
	touch $@

$(BUSYBOX_HOST_BINARY): $(BUSYBOX_HOST_DIR)/.configured
	$(TOOL_SUBMAKE) CC="$(TOOLS_CC)" CXX="$(TOOLS_CXX)" CFLAGS="$(TOOLS_CFLAGS)" LDFLAGS="$(TOOLS_LDFLAGS)" -C $(BUSYBOX_HOST_DIR)

$(BUSYBOX_HOST_TARGET_BINARY): $(BUSYBOX_HOST_BINARY)
	$(INSTALL_FILE)
	find $(BUSYBOX_HOST_TARGET_DIR) -lname busybox -delete
	for i in $$($(BUSYBOX_HOST_TARGET_BINARY) --list); do \
		ln -fs busybox $(BUSYBOX_HOST_TARGET_DIR)/$$i; \
	done

busybox-host-precompiled: $(BUSYBOX_HOST_TARGET_BINARY)


busybox-host-clean:
	-$(MAKE) -C $(BUSYBOX_HOST_DIR) clean

busybox-host-dirclean:
	$(RM) -r $(BUSYBOX_HOST_DIR)

busybox-host-distclean: busybox-host-dirclean
	find $(BUSYBOX_HOST_TARGET_DIR) \( -lname busybox -o -name busybox \) -delete

