PACKAGE_LC:=ldd
PACKAGE_UC:=LDD
$(PACKAGE_UC)_VERSION:=0.1
$(PACKAGE_INIT_BIN)
$(PACKAGE_UC)_SOURCE:=ldd-$($(PACKAGE_UC)_VERSION).tar.bz2
$(PACKAGE_UC)_SITE:=http://dsmod.magenbrot.net
$(PACKAGE_UC)_SOURCE_FILE:=$($(PACKAGE_UC)_DIR)/ldd.c
$(PACKAGE_UC)_BINARY:=$($(PACKAGE_UC)_DIR)/ldd
$(PACKAGE_UC)_TARGET_BINARY:=$($(PACKAGE_UC)_DEST_DIR)/usr/bin/ldd

$(PACKAGE_SOURCE_DOWNLOAD)
$(PACKAGE_UNPACKED)
$(PACKAGE_CONFIGURED_NOP)

$($(PACKAGE_UC)_BINARY): $($(PACKAGE_UC)_DIR)/.configured
	PATH="$(TARGET_PATH)" \
	    $(TARGET_CC) \
	    $(TARGET_CFLAGS) \
	    -DUCLIBC_RUNTIME_PREFIX=\ \
	    $(LDD_SOURCE_FILE) -o $@ 

$($(PACKAGE_UC)_TARGET_BINARY): $($(PACKAGE_UC)_BINARY)
	mkdir -p $(dir $(LDD_TARGET_BINARY))
	$(INSTALL_BINARY_STRIP)

ldd:

ldd-precompiled: uclibc ldd $($(PACKAGE_UC)_TARGET_BINARY)

ldd-clean:
	-$(MAKE) -C $(LDD_DIR) clean
	$(RM) $(PACKAGES_BUILD_DIR)/$(LDD_PKG_SOURCE)

ldd-uninstall:
	$(RM) $(LDD_TARGET_BINARY)

$(PACKAGE_FINI)
