#!/bin/sh

cat << EOF
if [ "$DAVFS2_MOUNTPOINT1" != "" ] 
then
  echo "unmount $DAVFS2_HOST1..."
  umount $DAVFS2_MOUNTPOINT1  
  sleep 3
  umount -l $DAVFS2_MOUNTPOINT1  2>/dev/null
  rmdir $DAVFS2_MOUNTPOINT1
fi

if [ "$DAVFS2_MOUNTPOINT2" != "" ]
then
  echo "unmount $DAVFS2_HOST2..."
  umount $DAVFS2_MOUNTPOINT2  
  sleep 3
  umount -l $DAVFS2_MOUNTPOINT2  2>/dev/null
  rmdir $DAVFS2_MOUNTPOINT2
fi

if [ "$DAVFS2_MOUNTPOINT3" != "" ]
then
  echo "unmount $DAVFS2_HOST3..."
  umount $DAVFS2_MOUNTPOINT3  
  sleep 3
  umount -l $DAVFS2_MOUNTPOINT3 2>/dev/null
  rmdir $DAVFS2_MOUNTPOINT3
fi

rm /var/cache/davfs2 2>/dev/null
rm -Rf /var/run/mount.davfs/
rmmod coda
EOF

