#!/bin/bash
# generates README/wiki/README.md and README/wiki/*/README.md
MYPWD="$(dirname $(realpath $0))"

echo -e "[//]: # ( Do not edit this file! Run generate.sh to create it. )\n\n# Wiki" > "$MYPWD/README.md"
for dir in $(find "$MYPWD" -mindepth 1 -type d | sed "s,^$MYPWD/,,g" | sort); do
	echo -e "[//]: # ( Do not edit this file! Run generate.sh to create it. )\n\n# ${dir#*_}" > "$MYPWD/$dir/README.md"
	echo -e "\n### [${dir#*_}]($dir/README.md)" >> "$MYPWD/README.md"
	for file in $(find "$MYPWD/$dir/" -name '*.md' | sed "s,.*/,,g" | sort | grep -v '^README.md$'); do
		dsc="$(sed -n '1 s/^# //p' "$MYPWD/$dir/$file")"
		[ "$file" != "${file%.en.md}" ] && dsc="$dsc [EN]"
		echo " - [$dsc]($dir/$file)" >> "$MYPWD/README.md"
		echo " - [$dsc]($file)" >> "$MYPWD/$dir/README.md"
		sed -n 's/^### //p' "$MYPWD/$dir/$file" | while read sub; do
			anc="$(echo "$sub" | sed -re 's/(.*)/\L\1/;s/[ _]/-/g;s/[^-0-9a-z]//g;s/--/-/g')"
			echo "    * [$sub]($file#$anc)" >> "$MYPWD/$dir/README.md"
		done
	done
	echo >> "$MYPWD/$dir/README.md"
done
echo >> "$MYPWD/README.md"

(
grep WikiDYN "$MYPWD/../../README.md" -B99 -A1
sed -rn 's/^### (\[.*\]\()(.*)/\1README\/wiki\/\2<br>/p' "$MYPWD/README.md"
grep WikiEND "$MYPWD/../../README.md" -A99 -B1
) > "$MYPWD/../../README_md"
mv "$MYPWD/../../README_md" "$MYPWD/../../README.md"
