PACKAGE_LC:=pingtunnel
PACKAGE_UC:=PINGTUNNEL
$(PACKAGE_UC)_VERSION:=0.61
$(PACKAGE_INIT_BIN)
PINGTUNNEL_SOURCE:=PingTunnel-$(PINGTUNNEL_VERSION).tar.gz
PINGTUNNEL_SITE:=http://www.cs.uit.no/~daniels/PingTunnel/
PINGTUNNEL_DIR:=$(SOURCE_DIR)/PingTunnel
PINGTUNNEL_BINARY:=$(PINGTUNNEL_DIR)/ptunnel
PINGTUNNEL_PKG_VERSION:=
PINGTUNNEL_TARGET_BINARY:=$(PINGTUNNEL_DEST_DIR)/usr/sbin/ptunnel

$(PACKAGE_SOURCE_DOWNLOAD)
$(PACKAGE_UNPACKED)
$(PACKAGE_CONFIGURED_NOP)

$($(PACKAGE_UC)_BINARY): $($(PACKAGE_UC)_DIR)/.configured
	PATH="$(TARGET_PATH)" \
		$(MAKE) -C $(PINGTUNNEL_DIR) \
		CC="$(TARGET_CC)" \
		CFLAGS="$(TARGET_CFLAGS) -DVERSION='\"$(PINGTUNNEL_VERSION)\"'" \
		LDOPTS="-lpthread -lpcap"

$($(PACKAGE_UC)_TARGET_BINARY): $($(PACKAGE_UC)_BINARY)
	$(INSTALL_BINARY_STRIP)

pingtunnel:

pingtunnel-precompiled: uclibc libpcap-precompiled pingtunnel $($(PACKAGE_UC)_TARGET_BINARY) 

pingtunnel-clean:
	-$(MAKE) -C $(PINGTUNNEL_DIR) clean
	rm -f $(PACKAGES_BUILD_DIR)/$(PINGTUNNEL_PKG_SOURCE)

pingtunnel-uninstall:
	rm -f $(PINGTUNNEL_TARGET_BINARY)
	
$(PACKAGE_FINI)
