PACKAGE_LC:=streamripper
PACKAGE_UC:=STREAMRIPPER
STREAMRIPPER_VERSION:=1.62.3
STREAMRIPPER_SOURCE:=streamripper-$(STREAMRIPPER_VERSION).tar.gz
STREAMRIPPER_SITE:=http://mesh.dl.sourceforge.net/sourceforge/streamripper
STREAMRIPPER_MAKE_DIR:=$(MAKE_DIR)/streamripper
STREAMRIPPER_DIR:=$(SOURCE_DIR)/streamripper-$(STREAMRIPPER_VERSION)
STREAMRIPPER_BINARY:=$(STREAMRIPPER_DIR)/streamripper
#STREAMRIPPER_PKG_VERSION:=0.1
STREAMRIPPER_TARGET_DIR:=$(PACKAGES_DIR)/streamripper-$(STREAMRIPPER_VERSION)
STREAMRIPPER_TARGET_BINARY:=$(STREAMRIPPER_TARGET_DIR)/root/usr/bin/streamripper
STREAMRIPPER_STARTLEVEL=40

$(PACKAGE_UC)_CONFIGURE_OPTIONS += --with-included-argv
$(PACKAGE_UC)_CONFIGURE_OPTIONS += --without-libiconv-prefix
$(PACKAGE_UC)_CONFIGURE_OPTIONS += --with-included-tre
$(PACKAGE_UC)_CONFIGURE_OPTIONS += --without-ogg
$(PACKAGE_UC)_CONFIGURE_OPTIONS += --without-vorbis
$(PACKAGE_UC)_CONFIGURE_OPTIONS += --disable-shared
#$(PACKAGE_UC)_CONFIGURE_OPTIONS += CFLAGS="$(TARGET_CFLAGS) -DANSI_PROTOTYPES"


$(PACKAGE_SOURCE_DOWNLOAD)
$(PACKAGE_BIN_UNPACKED)
$(PACKAGE_CONFIGURED_CONFIGURE)

$(STREAMRIPPER_BINARY): $(STREAMRIPPER_DIR)/.configured
	PATH="$(TARGET_PATH)" \
		$(MAKE) -C $(STREAMRIPPER_DIR) all

$(STREAMRIPPER_TARGET_BINARY): $(STREAMRIPPER_BINARY)
	mkdir -p $(dir $(STREAMRIPPER_TARGET_BINARY))
	$(INSTALL_BINARY_STRIP)

streamripper: 

streamripper-precompiled: uclibc mad-precompiled streamripper $(STREAMRIPPER_TARGET_BINARY)

streamripper-source: $(STREAMRIPPER_DIR)/.unpacked

streamripper-clean:
	-$(MAKE) -C $(STREAMRIPPER_DIR) clean

streamripper-dirclean:
	rm -rf $(STREAMRIPPER_DIR)

streamripper-uninstall:
	rm -f $(STREAMRIPPER_TARGET_BINARY)

$(PACKAGE_LIST)
