#!/bin/sh

cat <<EOF
#
#default {
#	default {
#		deny spoof
#		deny spoof_all
#		deny spoof_privport
#		allow random_numeric
#		allow numeric
#		allow hide
#	}
#}
#global {
#	reply "unknown"
#}
#
#user root {
#	default {
#		force reply "UNKNOWN"
#	}
#}
#
EOF
