#!/bin/sh

echo "/:$MOD_HTTPD_USER:$MOD_HTTPD_PASSWD"
# protect file servers.php to be viewed in clear text via URL with a fantasy password
[ -h /usr/mww/phpxmail/servers.php ] && echo "/phpxmail/servers.php:$MOD_HTTPD_USER:76advw6djc734hwh"
local php_cgi=$(which php-cgi)
[ -x "${php_cgi}" ] && echo "*.php:${php_cgi}"
