#!/bin/sh

echo "/:$MOD_HTTPD_USER:$MOD_HTTPD_PASSWD"
local php_cgi="$(which php-cgi)"
if [ -x "${php_cgi}" ]; then
	local php_wrapper="$(which php-wrapper)"
	if [ -x "${php_wrapper}" ]; then
		echo "*.php:${php_wrapper}"
	else
		echo "*.php:${php_cgi}"
	fi
fi
