#!/bin/sh

cat <<EOF
#
#global {
#reply "unknown" 
#} 
#
#Reply with "unknown" to all successful ident lookups. 
#
#
#to irc.example.org {
#
#reply "example" 
#} 
#
#Reply with "example" to ident lookups for connections to irc.example.org.
#
EOF
