#!/bin/sh

#
# Architecture / endianness specific values
#

# Machine
ac_cv_c_littleendian=no
ac_cv_c_bigendian=yes

# Types and sizes
ac_cv_sizeof_fpos_t=24

#
# Common values for all architectures
#
. $FREETZ_BASE_DIR/include/site/common-linux-uclibc
