PACKAGE_LC:=ctorrent
PACKAGE_UC:=CTORRENT
CTORRENT_VERSION:=dnh3.2
CTORRENT_SOURCE:=ctorrent-$(CTORRENT_VERSION).tar.gz
CTORRENT_SITE:=http://www.rahul.net/dholmes/ctorrent/
CTORRENT_MAKE_DIR:=$(MAKE_DIR)/ctorrent
CTORRENT_DIR:=$(SOURCE_DIR)/ctorrent-$(CTORRENT_VERSION)
CTORRENT_BINARY:=$(CTORRENT_DIR)/ctorrent
CTORRENT_TARGET_DIR:=$(PACKAGES_DIR)/ctorrent-$(CTORRENT_VERSION)
CTORRENT_TARGET_BINARY:=$(CTORRENT_TARGET_DIR)/root/usr/bin/ctorrent
CTORRENT_PKG_VERSION:=0.1
CTORRENT_STARTLEVEL=40

$(PACKAGE_UC)_CONFIGURE_ENV += CXXFLAGS="-Os"
$(PACKAGE_UC)_CONFIGURE_ENV += CXX="mipsel-linux-g++-uc"
$(PACKAGE_UC)_CONFIGURE_OPTIONS += --with-ssl=no


$(PACKAGE_SOURCE_DOWNLOAD)
$(PACKAGE_BIN_UNPACKED)
$(PACKAGE_CONFIGURED_CONFIGURE)
		
$(CTORRENT_BINARY): $(CTORRENT_DIR)/.configured
	PATH="$(TARGET_PATH)" \
		$(MAKE) -C $(CTORRENT_DIR) all

$(CTORRENT_TARGET_BINARY): $(CTORRENT_BINARY)
	mkdir -p $(dir $(CTORRENT_TARGET_BINARY))
	$(INSTALL_BINARY_STRIP)

ctorrent: 

ctorrent-precompiled: uclibc uclibcxx-precompiled ctorrent $(CTORRENT_TARGET_BINARY)

ctorrent-source: $(CTORRENT_DIR)/.unpacked

ctorrent-clean:
	-$(MAKE) -C $(CTORRENT_DIR) clean

ctorrent-dirclean:
	rm -rf $(CTORRENT_DIR)
	rm -rf $(PACKAGES_DIR)/ctorrent-$(CTORRENT_VERSION)

ctorrent-uninstall:
	rm -f $(CTORRENT_TARGET_BINARY)

$(PACKAGE_LIST)
