PACKAGE_LC:=modcgi
PACKAGE_UC:=MDOCGI
$(PACKAGE_UC)_VERSION:=0.2
$(PACKAGE_INIT_BIN)
$(PACKAGE_UC)_SOURCE:=modcgi-$($(PACKAGE_UC)_VERSION).tar.bz2
$(PACKAGE_UC)_SITE:=http://dsmod.magenbrot.net
$(PACKAGE_UC)_BINARY:=$($(PACKAGE_UC)_DIR)/modcgi
$(PACKAGE_UC)_TARGET_BINARY:=$($(PACKAGE_UC)_DEST_DIR)/usr/bin/modcgi


$(PACKAGE_SOURCE_DOWNLOAD)
$(PACKAGE_UNPACKED)
$(PACKAGE_CONFIGURED_NOP)

$($(PACKAGE_UC)_BINARY): $($(PACKAGE_UC)_DIR)/.configured
	PATH="$(TARGET_PATH)" \
		$(MAKE) -C $(MODCGI_DIR) \
		CROSS="$(TARGET_MAKE_PATH)/$(TARGET_CROSS)" \
		CFLAGS="$(TARGET_CFLAGS)" \
		LDFLAGS=""

$($(PACKAGE_UC)_TARGET_BINARY): $($(PACKAGE_UC)_BINARY)
	$(INSTALL_BINARY_STRIP)

modcgi-precompiled: uclibc $($(PACKAGE_UC)_TARGET_BINARY)

modcgi-clean:
	-$(MAKE) -C $(MODCGI_DIR) clean

modcgi-uninstall:
	rm -f $(MODCGI_TARGET_BINARY)

$(PACKAGE_FINI)
