#!/bin/sh

cat <<EOF
[Global]
	Name = irc.example.net
	;AdminInfo1 = Description
	;AdminInfo2 = Location
	;AdminEMail = admin@irc.server
	Info = Server Info Text
	;Listen = 127.0.0.1,192.168.0.1
	;MotdFile = /opt/ngircd/alex.git/etc/ngircd.motd
	;MotdPhrase = "Hello world!"
	;Password = abc
	;PidFile = /var/run/ngircd/ngircd.pid
	;Ports = 6667, 6668, 6669
	;ServerGID = 65534
	;ServerUID = 65534

[Limits]
	;ConnectRetry = 60
	;MaxConnections = 0
	;MaxConnectionsIP = 5
	;MaxJoins = 10
	;MaxNickLength = 9
	;PingTimeout = 120
	;PongTimeout = 20

[Options]
	;AllowRemoteOper = no
	;ChrootDir = /var/empty
	;CloakHost = irc.example.net
	;CloakUserToNick = yes
	;ConnectIPv6 = yes
	;ConnectIPv4 = yes
	;DNS = yes
	;Ident = yes
	;MorePrivacy = no
	;NoticeAuth = no
	;OperCanUseMode = no
	;OperServerMode = no
	;PAM = no
	;PredefChannelsOnly = no
	;RequireAuthPing = no
	;ScrubCTCP = no
	;SyslogFacility = local1
	;WebircPassword = xyz

;[SSL]
	;CertFile = /opt/ngircd/alex.git/etc/ssl/server-cert.pem
	;DHFile = /opt/ngircd/alex.git/etc/ssl/dhparams.pem
	;KeyFile = /opt/ngircd/alex.git/etc/ssl/server-key.pem
	;KeyFilePassword = secret
	;Ports = 6697, 9999

[Operator]
	;Name = TheOper
	;Password = ThePwd
	;Mask = *!ident@somewhere.example.com

[Operator]
	# More [Operator] sections, if you like ...

[Server]
	;Name = irc2.example.net
	;Host = connect-to-host.example.net
	;Bind = 10.0.0.1
	;Port = 6667
	;MyPassword = MySecret
	;PeerPassword = PeerSecret
	;Group = 123
	;Passive = no
	;SSLConnect = yes
	;ServiceMask = *Serv

[Server]
	# More [Server] sections, if you like ...

[Channel]
	;Name = #TheName
	;Topic = a great topic
	;Modes = tnk
	;Key = Secret
	;KeyFile = /opt/ngircd/alex.git/etc/#chan.key
	;MaxUsers = 23

[Channel]
	# More [Channel] sections, if you like ...

# -eof-
EOF
