#!/bin/sh
. /usr/lib/libmodredir.sh
plport="$(grep -A9 '^webinterface -' /mod/pyload/pyload.conf 2>/dev/null | sed -n 's/.*"Port" = \([0-9]*\).*/\1/p' | head -n1)"

redirect "http://$(self_host):${plport:-8000}/" "pyload"
