#!/bin/sh

cat <<EOF
ip = "$BIP_IP";
port = "$BIP_PORT";
pid_file = "/var/run/bip.pid";
log = $BIP_LOG;
log_level = $BIP_LOG_LEVEL;
log_root = "$BIP_LOG_ROOT";
log_system = $BIP_LOG_SYSTEM;
log_format = "$BIP_LOG_FORMAT";
EOF
