#!/bin/sh

cat <<EOF
ip = "192.168.178.1";
port = 6667;
log = true;
#the "log_root"-directory has to be available
log_root = "/var/media/ftp/uStor01/bip";
log_system = true;
log_sync_interval = 250;
log_level = 3;
# please do not change the "pid_file"
pid_file="/var/run/bip.pid";

# put your networks and users here (see documentation):

EOF

