#!/bin/sh

cat <<EOF
confdir /mod/etc/privoxy
actionsfile default.action
filterfile default.filter
enable-edit-actions 0
logdir /var/log
logfile privoxy.log
# debug   4096
debug   8192
EOF

[ -r "/tmp/flash/privoxy/user.action" ] && echo "actionsfile /tmp/flash/privoxy/user.action"

[ -r "/tmp/flash/privoxy/user.filter" ] && echo "filterfile /tmp/flash/privoxy/user.filter"

echo "toggle $PRIVOXY_TOGGLE"
echo "enable-remote-toggle $PRIVOXY_ENABLE_REMOTE_TOGGLE"
echo "enforce-blocks $PRIVOXY_ENFORCE_BLOCKS"

echo "listen-address $PRIVOXY_LISTEN_ADDRESS:$PRIVOXY_LISTEN_PORT"

[ "$PRIVOXY_FORWARD_SOCKS" ] && echo "forward-socks4a / $PRIVOXY_FORWARD_SOCKS ."

if [ ! -z "$PRIVOXY_PERMIT_ACCESS" ]; then
	echo "$PRIVOXY_PERMIT_ACCESS" | grep -v "^#" | while read -r permit; do
		[ -n "$permit" ] && echo "permit-access $permit"
	done
	echo ""
fi

if [ ! -z "$PRIVOXY_DENY_ACCESS" ]; then
	echo "$PRIVOXY_DENY_ACCESS" | grep -v "^#" | while read -r deny; do
		[ -n "$deny" ] && echo "deny-access $deny"
	done
	echo ""
fi
