#!/bin/sh

cat <<EOF
confdir /mod/etc/privoxy
actionsfile match-all.action
actionsfile default.action
filterfile default.filter
enable-edit-actions 0
tolerate-pipelining 1
EOF

echo "logdir $PRIVOXY_LOGDIR"
echo "logfile $PRIVOXY_LOGFILE"
echo "debug $PRIVOXY_LOGLEVEL"

if [ -n "${PRIVOXY_ALT_PATH// /}" ]; then
	MYPATH=${PRIVOXY_ALT_PATH}
else
	MYPATH="/tmp/flash/privoxy"
fi
[ -r "${MYPATH}/user.action" ] && echo "actionsfile ${MYPATH}/user.action"
[ -r "${MYPATH}/user.filter" ] && echo "filterfile ${MYPATH}/user.filter"

echo "toggle $PRIVOXY_TOGGLE"
echo "enable-remote-toggle $PRIVOXY_ENABLE_REMOTE_TOGGLE"
echo "enforce-blocks $PRIVOXY_ENFORCE_BLOCKS"

echo "allow-cgi-request-crunching $PRIVOXY_CGI_CRUNCH"

echo "listen-address $PRIVOXY_LISTEN_ADDRESS:$PRIVOXY_LISTEN_PORT"

[ "$PRIVOXY_FORWARD_SOCKS" ] && echo "forward-${PRIVOXY_FORWARD_SOCKS_TYPE} / $PRIVOXY_FORWARD_SOCKS ."

if [ ! -z "$PRIVOXY_PERMIT_ACCESS" ]; then
	echo "$PRIVOXY_PERMIT_ACCESS" | grep -v "^#" | while read -r permit; do
		[ -n "$permit" ] && echo "permit-access $permit"
	done
	echo ""
fi

if [ ! -z "$PRIVOXY_DENY_ACCESS" ]; then
	echo "$PRIVOXY_DENY_ACCESS" | grep -v "^#" | while read -r deny; do
		[ -n "$deny" ] && echo "deny-access $deny"
	done
	echo ""
fi
