PACKAGE_LC:=bridge-utils
PACKAGE_UC:=BRIDGE_UTILS
BRIDGE_UTILS_VERSION:=1.2
BRIDGE_UTILS_SOURCE:=bridge-utils-$(BRIDGE_UTILS_VERSION).tar.gz
BRIDGE_UTILS_SITE:=http://mesh.dl.sourceforge.net/sourceforge/bridge
BRIDGE_UTILS_MAKE_DIR:=$(MAKE_DIR)/bridge-utils
BRIDGE_UTILS_DIR:=$(SOURCE_DIR)/bridge-utils-$(BRIDGE_UTILS_VERSION)
BRIDGE_UTILS_BINARY:=$(BRIDGE_UTILS_DIR)/brctl/brctl
BRIDGE_UTILS_TARGET_DIR:=$(PACKAGES_DIR)/bridge-utils-$(BRIDGE_UTILS_VERSION)
BRIDGE_UTILS_TARGET_BINARY:=$(BRIDGE_UTILS_TARGET_DIR)/root/sbin/brctl
BRIDGE_UTILS_STARTLEVEL=90 # for PACKAGE_LIST, no autostart

$(PACKAGE_UC)_CONFIGURE_PRE_CMDS:=
$(PACKAGE_UC)_CONFIGURE_PRE_CMDS += aclocal --force ;
$(PACKAGE_UC)_CONFIGURE_PRE_CMDS += libtoolize --force ;
$(PACKAGE_UC)_CONFIGURE_PRE_CMDS += autoconf --force ;
$(PACKAGE_UC)_CONFIGURE_PRE_CMDS += autoheader --force ;

$(PACKAGE_UC)_CONFIGURE_OPTIONS:=
$(PACKAGE_UC)_CONFIGURE_OPTIONS += --with-randomdev=/dev/random
$(PACKAGE_UC)_CONFIGURE_OPTIONS += --with-linux-headers=$(KERNEL_DIR)/linux/include


$(PACKAGE_SOURCE_DOWNLOAD)
$(PACKAGE_BIN_UNPACKED)
$(PACKAGE_CONFIGURED_CONFIGURE)

$(BRIDGE_UTILS_BINARY): $(BRIDGE_UTILS_DIR)/.configured
	PATH="$(TARGET_PATH)" $(MAKE) -C $(BRIDGE_UTILS_DIR)

$(BRIDGE_UTILS_TARGET_BINARY): $(BRIDGE_UTILS_BINARY)
	mkdir -p $(dir $(BRIDGE_UTILS_TARGET_BINARY))
	$(INSTALL_BINARY_STRIP)

bridge-utils: uclibc $(BRIDGE_UTILS_TARGET_BINARY)

bridge-utils-precompiled: bridge-utils $(BRIDGE_UTILS_TARGET_BINARY)

#bridge-utils-source: $(BRIDGE_UTILS_DIR)/.unpacked $(PACKAGES_DIR)/.bridge-utils-$(BRIDGE_UTILS_VERSION)

bridge-utils-clean:
	-$(MAKE) -C $(BRIDGE_UTILS_DIR) clean
#	rm -f $(PACKAGES_BUILD_DIR)/$(BRIDGE_UTILS_PKG_SOURCE)

bridge-utils-dirclean:
	rm -rf $(BRIDGE_UTILS_DIR)
	rm -rf $(PACKAGES_DIR)/bridge-utils-$(BRIDGE_UTILS_VERSION)
	rm -f $(PACKAGES_DIR)/.bridge-utils-$(BRIDGE_UTILS_VERSION)

bridge-utils-uninstall:
	rm -f $(BRIDGE_UTILS_TARGET_BINARY)


$(PACKAGE_LIST)
