#! /bin/sh
[ -r "/mod/etc/conf/mod.cfg" ] && . /mod/etc/conf/mod.cfg || exit $?

mode=${1:-start}

[ "$mode" = start ] && modreg status mod 'Freetz$(lang de:"-Logs" en:" logs")' logs
[ "$mode" = start ] && modreg status mod 'AVM$(lang de:"-Logs" en:" logs")' logs_avm

[ "$mode" = reload ] && modunreg status mod mounted
if [ "$MOD_MOUNTED_SUB" = yes ]; then
	modreg status mod '$(lang de:"Partitionen" en:"Partitions")' mounted
fi

[ "$mode" = reload ] && modunreg status mod box_info
if [ "$MOD_SHOW_BOX_INFO" = yes -a -r "/usr/lib/cgi-bin/mod/box_info.cgi" ]; then
	modreg status mod 'Box$(lang de:"-Info" en:" info")' box_info
fi

[ "$mode" = reload ] && modunreg status mod info
if [ "$MOD_SHOW_FREETZ_INFO" = yes -a -r "/usr/lib/cgi-bin/mod/info.cgi" ]; then
	modreg status mod 'Freetz$(lang de:"-Info" en:" info")' info
fi
