#!/bin/sh

cat << EOF
# stunnel config

foreground = no
pid = /var/run/stunnel.pid
client = yes

cert = /tmp/flash/stunnel/certs.pem
key = /tmp/flash/stunnel/key.pem

RNDbytes = 1024
RNDfile = /var/tmp/.stunnel_rnd
RNDoverwrite = yes

socket = a:TCP_NODELAY=1
EOF

if [ ! -z "$STUNNEL_SSLOPTIONS" ]; then
	echo "options = $STUNNEL_SSLOPTIONS"
fi

if [ ! -z "$STUNNEL_VERBOSE" ]; then
	echo "debug = $STUNNEL_VERBOSE"
fi
