#!/bin/sh

[ -r /etc/options.cfg ] && . /etc/options.cfg

cat << EOF
# Have a look at
# http://siproxd.sourceforge.net/index.php?op=odoc
# and
# http://siproxd.sourceforge.net/index.php?op=faq
# for more information!
#
# Below is a minimal set of parameters for siproxd.
# You must change/add parameters to fit your needs.
# Don't use 5060/5061 as sip_listen_port, AVM uses
# these ports for its own VoIP solution.
if_inbound  = lan
if_outbound = lan
sip_listen_port = 55060
user = siproxd
silence_log = 1
registration_file = /tmp/flash/siproxd/siproxd.reg
plugindir=${FREETZ_LIBRARY_DIR}/siproxd
load_plugin=plugin_logcall.la
EOF
