#!/bin/sh

cat <<EOF
# client name (CN)	server name (CN)	client cert	server cert			CA cert			server key			IP addresses
*			fritzbox		-		/tmp/flash/ppp/server.crt	/tmp/flash/ppp/ca.crt	/tmp/flash/ppp/server.key	*
EOF
