PACKAGE_LC:=haserl
PACKAGE_UC:=HASERL
$(PACKAGE_UC)_VERSION:=0.9.20
$(PACKAGE_INIT_BIN)
$(PACKAGE_UC)_SOURCE:=haserl-$($(PACKAGE_UC)_VERSION).tar.gz
$(PACKAGE_UC)_SITE:=http://mesh.dl.sourceforge.net/sourceforge/haserl
$(PACKAGE_UC)_DIR:=$(SOURCE_DIR)/haserl-$($(PACKAGE_UC)_VERSION)
$(PACKAGE_UC)_MAKE_DIR:=$(MAKE_DIR)/haserl
$(PACKAGE_UC)_BINARY:=$($(PACKAGE_UC)_DIR)/src/haserl
$(PACKAGE_UC)_TARGET_DIR:=root/usr/bin
$(PACKAGE_UC)_TARGET_BINARY:=$($(PACKAGE_UC)_TARGET_DIR)/haserl


$(PACKAGE_SOURCE_DOWNLOAD)
$(PACKAGE_UNPACKED)
$(PACKAGE_CONFIGURED_CONFIGURE)

$($(PACKAGE_UC)_BINARY): $($(PACKAGE_UC)_DIR)/.configured
	PATH="$(TARGET_PATH)" \
		$(MAKE) -C $(HASERL_DIR) \
		CROSS="$(TARGET_MAKE_PATH)/$(TARGET_CROSS)" \
		CFLAGS="$(TARGET_CFLAGS)" 

$($(PACKAGE_UC)_TARGET_BINARY): $($(PACKAGE_UC)_BINARY)
	$(INSTALL_BINARY_STRIP)

haserl-precompiled: uclibc $($(PACKAGE_UC)_TARGET_BINARY)

haserl-clean:
	-$(MAKE) -C $(HASERL_DIR) clean

haserl-uninstall:
	rm -f $(HASERL_TARGET_BINARY)

$(PACKAGE_FINI)
