PACKAGE_LC:=haserl
PACKAGE_UC:=HASERL
HASERL_VERSION:=0.9.20
HASERL_SOURCE:=haserl-$(HASERL_VERSION).tar.gz
HASERL_SITE:=http://mesh.dl.sourceforge.net/sourceforge/haserl
HASERL_DIR:=$(SOURCE_DIR)/haserl-$(HASERL_VERSION)
HASERL_MAKE_DIR:=$(MAKE_DIR)/haserl
HASERL_BINARY:=$(HASERL_DIR)/src/haserl
HASERL_TARGET_DIR:=root/usr/bin
HASERL_TARGET_BINARY:=$(HASERL_TARGET_DIR)/haserl


$(PACKAGE_SOURCE_DOWNLOAD)
$(PACKAGE_UNPACKED)
$(PACKAGE_CONFIGURED_CONFIGURE)

$(HASERL_BINARY): $(HASERL_DIR)/.configured
	PATH="$(TARGET_PATH)" \
		$(MAKE) -C $(HASERL_DIR) \
		CROSS="$(TARGET_MAKE_PATH)/$(TARGET_CROSS)" \
		CFLAGS="$(TARGET_CFLAGS)" 

$(HASERL_TARGET_BINARY): $(HASERL_BINARY)
	$(INSTALL_BINARY_STRIP)

haserl-precompiled: uclibc $(HASERL_TARGET_BINARY)

haserl-source: $(HASERL_DIR)/.unpacked

haserl-clean:
	-$(MAKE) -C $(HASERL_DIR) clean

haserl-uninstall:
	rm -f $(HASERL_TARGET_BINARY)

haserl-dirclean:
	rm -rf $(HASERL_DIR)
