$(call PKG_INIT_LIB, 1.0)

$(PKG)_BINARY:=$($(PKG)_DIR)/$(pkg).so.$($(PKG)_VERSION)
$(PKG)_TARGET_BINARY:=$($(PKG)_DEST_LIB)/$(pkg).so.$($(PKG)_VERSION)

$(PKG)_REBUILD_SUBOPTS += FREETZ_TARGET_UCLIBC_MAJOR_VERSION
$(PKG)_REBUILD_SUBOPTS += FREETZ_LIB_libctlmgr_WITH_CHMOD
$(PKG)_REBUILD_SUBOPTS += FREETZ_LIB_libctlmgr_WITH_RENAME
$(PKG)_REBUILD_SUBOPTS += FREETZ_AVM_PROP_LIBC_GLIBC
$(PKG)_REBUILD_SUBOPTS += FREETZ_AVM_PROP_LIBC_MUSL
$(PKG)_REBUILD_SUBOPTS += FREETZ_AVM_PROP_LIBC_UCLIBC

#$(PKG)_CPPFLAGS += -DDEBUG
$(PKG)_CPPFLAGS += $(if $(FREETZ_LIB_libctlmgr_WITH_CHMOD),-DD_CHMOD)
$(PKG)_CPPFLAGS += $(if $(FREETZ_LIB_libctlmgr_WITH_RENAME),-DD_RENAME)
$(PKG)_CPPFLAGS += $(if $(FREETZ_AVM_PROP_LIBC_GLIBC),-DD_GLIBC)
$(PKG)_CPPFLAGS += $(if $(FREETZ_AVM_PROP_LIBC_MUSL),-DD_MUSL)
$(PKG)_CPPFLAGS += $(if $(FREETZ_AVM_PROP_LIBC_UCLIBC),-DD_UCLIBC)


$(PKG_LOCALSOURCE_PACKAGE)
$(PKG_CONFIGURED_NOP)

$($(PKG)_BINARY): $($(PKG)_DIR)/.configured
	$(SUBMAKE) -C $(LIBCTLMGR_DIR) \
		CC="$(TARGET_CC)" \
		CFLAGS="$(TARGET_CFLAGS)" \
		CPPFLAGS="$(strip $(LIBCTLMGR_CPPFLAGS))" \
		LIB_VERSION="$(LIBCTLMGR_VERSION)" \
		all
	$(FREETZ_BASE_DIR)/$(TOOLS_DIR)/patchelf --remove-rpath $@

$($(PKG)_TARGET_BINARY): $($(PKG)_BINARY)
	$(INSTALL_LIBRARY_STRIP)

$(pkg):

$(pkg)-precompiled: $($(PKG)_TARGET_BINARY)


$(pkg)-clean:
	-$(SUBMAKE) -C $(LIBCTLMGR_DIR) clean

$(pkg)-uninstall:
	$(RM) $(LIBCTLMGR_DEST_LIB)/libctlmgr*.so*

$(PKG_FINISH)
