PACKAGE_LC:=strace
PACKAGE_UC:=STRACE
$(PACKAGE_UC)_VERSION:=4.5.15
$(PACKAGE_INIT_BIN)
STRACE_SOURCE:=strace-$(STRACE_VERSION).tar.bz2
STRACE_SITE:=http://mesh.dl.sourceforge.net/sourceforge/strace
STRACE_BINARY:=$(STRACE_DIR)/strace
STRACE_TARGET_BINARY:=$(STRACE_DEST_DIR)/usr/sbin/strace

$(PACKAGE_SOURCE_DOWNLOAD)
$(PACKAGE_UNPACKED)
$(PACKAGE_CONFIGURED_CONFIGURE)

$($(PACKAGE_UC)_BINARY): $($(PACKAGE_UC)_DIR)/.configured
	PATH="$(TARGET_PATH)" \
		$(MAKE) -C $(STRACE_DIR)

$($(PACKAGE_UC)_TARGET_BINARY): $($(PACKAGE_UC)_BINARY)
	$(INSTALL_BINARY_STRIP)

strace:

strace-precompiled: uclibc strace $($(PACKAGE_UC)_TARGET_BINARY)

strace-clean:
	-$(MAKE) -C $(STRACE_DIR) clean
	rm -f $(PACKAGES_BUILD_DIR)/$(STRACE_PKG_SOURCE)

strace-uninstall:
	rm -f $(STRACE_TARGET_BINARY)
	
$(PACKAGE_FINI)