#!/bin/sh
#busybox nhttpd needs that "Content-type: text/html" is at first line,
#so we make a trick. If anyone has a better idea -> feel free to edit.

content="$(/usr/bin/php-cgi $*)"
echo "$content"|grep -e "^Content-type: .*"
echo "$content"|grep -ve "^Content-type: .*"
