--- Makefile.orig	2006-01-06 18:13:59.650422040 +0100
+++ Makefile	2006-01-06 18:15:17.237626992 +0100
@@ -23,29 +23,29 @@
 MANDIR=$(PREFIX)/share/man
 
 CC=gcc
-CFLAGS=-W -Wall -O -g '-DVERSION="$(shell cat VERSION)"' $(shell libgcrypt-config --cflags)
-LDFLAGS=-g $(shell libgcrypt-config --libs)
+CFLAGS=$(EXTRA_CFLAGS) -g '-DVERSION="$(shell cat VERSION)"'
+LDFLAGS=$(EXTRA_LDFLAGS) -g -lgcrypt -lgpg-error
 
-ifeq ($(shell uname -s), Linux)
+#ifeq ($(shell uname -s), Linux)
 SYSDEP=sysdep-linux.o
-endif
-ifeq ($(shell uname -s), FreeBSD)
-CFLAGS += -DSOCKADDR_IN_SIN_LEN -DHAVE_SA_LEN
-SYSDEP=sysdep-bsd.o
-endif
-ifeq ($(shell uname -s), NetBSD)
-CFLAGS += -DSOCKADDR_IN_SIN_LEN -DHAVE_SA_LEN
-SYSDEP=sysdep-bsd.o
-endif
-ifeq ($(shell uname -s), OpenBSD)
-CFLAGS += -DSOCKADDR_IN_SIN_LEN -DHAVE_SA_LEN -DNEED_IPLEN_FIX -DNEW_TUN
-SYSDEP=sysdep-bsd.o
-endif
-ifeq ($(shell uname -s), SunOS)
-CFLAGS += -DNEED_IPLEN_FIX
-LDFLAGS += -lnsl -lresolv -lsocket
-SYSDEP=sysdep-svr4.o
-endif
+#endif
+#ifeq ($(shell uname -s), FreeBSD)
+#CFLAGS += -DSOCKADDR_IN_SIN_LEN -DHAVE_SA_LEN
+#SYSDEP=sysdep-bsd.o
+#endif
+#ifeq ($(shell uname -s), NetBSD)
+#CFLAGS += -DSOCKADDR_IN_SIN_LEN -DHAVE_SA_LEN
+#SYSDEP=sysdep-bsd.o
+#endif
+#ifeq ($(shell uname -s), OpenBSD)
+#CFLAGS += -DSOCKADDR_IN_SIN_LEN -DHAVE_SA_LEN -DNEED_IPLEN_FIX -DNEW_TUN
+#SYSDEP=sysdep-bsd.o
+#endif
+#ifeq ($(shell uname -s), SunOS)
+#CFLAGS += -DNEED_IPLEN_FIX
+#LDFLAGS += -lnsl -lresolv -lsocket
+#SYSDEP=sysdep-svr4.o
+#endif
 
 FILELIST := $(shell echo *.c *.h vpnc-*) Makefile README ChangeLog COPYING TODO VERSION vpnc.conf vpnc.8 pcf2vpnc
 
