#!/bin/sh
#by cuma
[ ! -r /var/mod/etc/conf/ppp.cfg ] && exit 1
. /var/mod/etc/conf/ppp.cfg

cd /tmp
while [ 1 ]; do
	echo -e "\n##\n`date "+%Y-%m-%d %H:%M,%S"`" >> $PPP_LOGFILE
	pppd call dun 2>&1 >> $PPP_LOGFILE
	sleep 1
done

