$(call PKG_INIT_BIN, 0.5)
$(PKG)_SOURCE:=knock-$($(PKG)_VERSION).tar.gz
$(PKG)_SITE:=http://www.zeroflux.org/proj/knock/files
$(PKG)_KNOCK_BINARY:=$($(PKG)_DIR)/knock
$(PKG)_KNOCKD_BINARY:=$($(PKG)_DIR)/knockd
$(PKG)_TARGET_KNOCK_BINARY:=$(KNOCK_DEST_DIR)/usr/bin/knock
$(PKG)_TARGET_KNOCKD_BINARY:=$(KNOCK_DEST_DIR)/usr/bin/knockd
$(PKG)_STARTLEVEL=80

$(PKG)_DEPENDS_ON := libpcap


$(PKG_SOURCE_DOWNLOAD)
$(PKG_UNPACKED)
$(PKG_CONFIGURED_CONFIGURE)

$(KNOCK_KNOCK_BINARY) $(KNOCK_KNOCKD_BINARY): $(KNOCK_DIR)/.configured
	PATH="$(TARGET_PATH)" \
		$(MAKE) -C $(KNOCK_DIR)

$(KNOCK_TARGET_KNOCK_BINARY): $(KNOCK_KNOCK_BINARY) 
	$(INSTALL_BINARY_STRIP)

$(KNOCK_TARGET_KNOCKD_BINARY): $(KNOCK_KNOCKD_BINARY) 
	$(INSTALL_BINARY_STRIP)

knock:

knock-precompiled: $(KNOCK_TARGET_KNOCK_BINARY) $(KNOCK_TARGET_KNOCKD_BINARY)

knock-clean:
	-$(MAKE) -C $(KNOCK_DIR) clean
	rm -f $(PACKAGES_BUILD_DIR)/$(KNOCK_PKG_SOURCE)

knock-uninstall: 
	rm -f $(KNOCK_TARGET_KNOCK_BINARY)
	rm -f $(KNOCK_TARGET_KNOCKD_BINARY)

$(PKG_FINISH)
