#!/bin/sh

cat << EOF
--syslog

--background

--username $INADYN_OPENDNS_USER

--password $INADYN_OPENDNS_PASS

--alias $INADYN_OPENDNS_ALIAS

--secure

--dyndns_server_name updates.opendns.com

--dyndns_server_url /nic/update?

EOF
