PACKAGE_LC:=sg3_utils
PACKAGE_UC:=SG3UTILS
SG3UTILS_VERSION:=1.24
SG3UTILS_SOURCE:=sg3_utils-$(SG3UTILS_VERSION).tgz
SG3UTILS_SITE:=http://sg.torque.net/sg/p/
SG3UTILS_MAKE_DIR:=$(MAKE_DIR)/sg3_utils
SG3UTILS_DIR:=$(SOURCE_DIR)/sg3_utils-$(SG3UTILS_VERSION)
SG3UTILS_BINARY:=$(SG3UTILS_DIR)/sg_start
SG3UTILS_PKG_VERSION:=0.1
SG3UTILS_PKG_NAME:=sg3_utils-$(SG3UTILS_VERSION)
SG3UTILS_TARGET_DIR:=$(PACKAGES_DIR)/$(SG3UTILS_PKG_NAME)
SG3UTILS_TARGET_BINARY:=$(SG3UTILS_TARGET_DIR)/root/usr/bin/sg_start
SG3UTILS_STARTLEVEL=40

$(PACKAGE_SOURCE_DOWNLOAD)
$(PACKAGE_BIN_UNPACKED)
$(PACKAGE_CONFIGURED_NOP)

$(SG3UTILS_BINARY): $(SG3UTILS_DIR)/.configured
	PATH="$(TARGET_PATH)" \
		CFLAGS="-DSG3_UTILS_LINUX $(TARGET_CFLAGS)" \
		CC="$(TARGET_CC)" \
		LD="$(TARGET_LD)" \
		$(MAKE) -f no_lib/Makefile.linux sg_start -C $(SG3UTILS_DIR)
	touch $@

$(SG3UTILS_TARGET_BINARY): $(SG3UTILS_BINARY)
	mkdir -p $(dir $(SG3UTILS_TARGET_BINARY))
	$(INSTALL_BINARY_STRIP)

sg3_utils:

sg3_utils-precompiled: uclibc sg3_utils $(SG3UTILS_TARGET_BINARY)

sg3_utils-source: $(SG3UTILS_DIR)/.unpacked

sg3_utils-clean:
	-$(MAKE) -C $(SG3UTILS_DIR) clean
	rm -f $(SG3UTILS_DIR)/.installed
	rm -f $(SG3UTILS_DIR)/.built
	rm -f $(SG3UTILS_DIR)/.configured
	rm -f $(PACKAGES_BUILD_DIR)/$(SG3UTILS_PKG_SOURCE)

sg3_utils-dirclean:
	rm -rf $(SG3UTILS_DIR)
	rm -rf $(PACKAGES_DIR)/$(SG3UTILS_PKG_NAME)

sg3_utils-uninstall:
	rm -f $(SG3UTILS_TARGET_BINARY)

$(PACKAGE_LIST)

