$(call PKG_INIT_BIN, 0.5)
$(PKG)_PRJNAME:=privatekeypassword
$(PKG)_SOURCE:=v$($(PKG)_VERSION).tar.gz
$(PKG)_SOURCE_SHA256:=353e1e868226bfba0e2bcf583dad79cd55231d38ec7cba381a3e7b0e6a0e3715
$(PKG)_SITE:=https://github.com/PeterPawn/$($(PKG)_PRJNAME)/archive

$(PKG)_BINARY:=$($(PKG)_DIR)/$($(PKG)_PRJNAME)
$(PKG)_TARGET_BINARY:=$($(PKG)_DEST_DIR)/usr/bin/$($(PKG)_PRJNAME)

$(PKG)_LIBNAME:=lib$($(PKG)_PRJNAME).so
$(PKG)_LIB_BINARY:=$($(PKG)_DIR)/$($(PKG)_LIBNAME)
$(PKG)_LIB_STAGING_BINARY:=$(TARGET_TOOLCHAIN_STAGING_DIR)/usr/lib/$($(PKG)_LIBNAME)
$(PKG)_LIB_TARGET_BINARY:=$($(PKG)_TARGET_LIBDIR)/$($(PKG)_LIBNAME)

$(PKG_SOURCE_DOWNLOAD)
$(PKG_UNPACKED)
$(PKG_CONFIGURED_NOP)

$($(PKG)_LIB_BINARY) $($(PKG)_BINARY): $($(PKG)_DIR)/.configured
	$(SUBMAKE) -C $(PRIVATEKEYPASSWORD_DIR) \
		CC="$(TARGET_CC)" \
		CFLAGS="$(TARGET_CFLAGS)" \
		AR="$(TARGET_AR)" \
		RANLIB="$(TARGET_RANLIB)"

$($(PKG)_LIB_STAGING_BINARY): $($(PKG)_LIB_BINARY)
	$(SUBMAKE) -C $(PRIVATEKEYPASSWORD_DIR) \
		DESTDIR="$(TARGET_TOOLCHAIN_STAGING_DIR)" \
		install-lib

$($(PKG)_TARGET_BINARY): $($(PKG)_BINARY)
	$(INSTALL_BINARY_STRIP)

$($(PKG)_LIB_TARGET_BINARY): $($(PKG)_LIB_STAGING_BINARY)
	$(INSTALL_LIBRARY_STRIP)

$(pkg):

$(pkg)-precompiled: $($(PKG)_TARGET_BINARY) $($(PKG)_LIB_TARGET_BINARY)

$(pkg)-clean:
	-$(SUBMAKE) -C $(PRIVATEKEYPASSWORD_DIR) clean
	$(RM) -r \
		$(TARGET_TOOLCHAIN_STAGING_DIR)/usr/lib/libprivatekeypassword* \
		$(TARGET_TOOLCHAIN_STAGING_DIR)/usr/include/privatekeypassword

$(pkg)-uninstall:
	$(RM) \
		$(PRIVATEKEYPASSWORD_TARGET_BINARY) \
		$(PRIVATEKEYPASSWORD_TARGET_LIBDIR)/libprivatekeypassword.so*

$(call PKG_ADD_LIB,libprivatekeypassword)
$(PKG_FINISH)
