#!/bin/sh
[ -r /etc/options.cfg ] && . /etc/options.cfg

[ "$SSLH_ENABLED" != "inetd" ] && echo 'inetd: false;' || echo 'inetd: true;'
cat << EOF
verbose: false;
foreground: false;
numeric: false;
timeout: ${SSLH_TIMEOUT:-0};
user: "nobody";
pidfile: "/var/run/sslh.pid";
EOF

echo 'listen:'
echo '('
for port in $SSLH_PORTS; do
	[ -n "$value" ] && echo "${value},"
	value="{ host: \"0.0.0.0\"; port: \"$port\"; }"
done
if [ "$FREETZ_TARGET_IPV6_SUPPORT" == "y" -a "$SSLH_IPV6TOO" == "yes" ]; then
for port in $SSLH_PORTS; do
	[ -n "$value" ] && echo "${value},"
	value="{ host: \"::\"; port: \"$port\"; }"
done
fi
echo "${value}"
echo ');'

echo 'protocols:'
echo '('
cat /tmp/flash/sslh/protocols 2>/dev/null
echo ');'

[ -n "$SSLH_ON_TIMEOUT" ] && echo "on-timeout: \"$SSLH_ON_TIMEOUT\";"
