#!/bin/sh

which wlancfgctl >/dev/null || return
DAVFS2_HOST0="$(webdavcfginfo -p host_url)"
DAVFS2_USER0="$(webdavcfginfo -p username)"
DAVFS2_PASS0="$(webdavcfginfo -p password)"

cat << EOF
$DAVFS2_HOST0 $DAVFS2_USER0 $DAVFS2_PASS0
EOF
