$(call PKG_INIT_BIN, 14.0)
$(PKG)_SOURCE:=$(pkg)-$($(PKG)_VERSION).tar.gz
$(PKG)_SITE:=@SF/$(pkg)
$(PKG)_BINARY:=$($(PKG)_DIR)/$(pkg)
$(PKG)_TARGET_BINARY:=$($(PKG)_DEST_DIR)/usr/bin/$(pkg)

$(PKG)_DEPENDS_ON := libxml2 uclibcxx zlib

$(PKG)_LDADD := -lxml2 -lz

ifeq ($(strip $(FREETZ_PACKAGE_NZBGET_WITH_CURSES)),y)
$(PKG)_DEPENDS_ON += ncurses
endif

ifeq ($(strip $(FREETZ_PACKAGE_NZBGET_WITH_TLS)),y)
$(PKG)_DEPENDS_ON += openssl
$(PKG)_LDADD += -lssl -lcrypto
endif

ifeq ($(strip $(FREETZ_PACKAGE_NZBGET_STATIC)),y)
$(PKG)_LDFLAGS := -static
$(PKG)_LDADD += -ldl -lm
endif

$(PKG)_REBUILD_SUBOPTS += FREETZ_PACKAGE_NZBGET_WITH_CURSES
$(PKG)_REBUILD_SUBOPTS += FREETZ_PACKAGE_NZBGET_WITH_TLS
$(PKG)_REBUILD_SUBOPTS += FREETZ_PACKAGE_NZBGET_DISABLE_PAR_CHECK
$(PKG)_REBUILD_SUBOPTS += FREETZ_PACKAGE_NZBGET_STATIC

$(PKG)_CONFIGURE_ENV += LIBPREF="$(TARGET_TOOLCHAIN_STAGING_DIR)/usr"

$(PKG)_CONFIGURE_OPTIONS += $(if $(FREETZ_PACKAGE_NZBGET_WITH_CURSES),,--disable-curses)
$(PKG)_CONFIGURE_OPTIONS += $(if $(FREETZ_PACKAGE_NZBGET_WITH_TLS),,--disable-tls)
$(PKG)_CONFIGURE_OPTIONS += --with-tlslib=OpenSSL
$(PKG)_CONFIGURE_OPTIONS += $(if $(FREETZ_PACKAGE_NZBGET_DISABLE_PAR_CHECK),--disable-parcheck,)
$(PKG)_CONFIGURE_OPTIONS += $(if $(FREETZ_PACKAGE_NZBGET_STATIC),--enable-static,--disable-static)

$(PKG_SOURCE_DOWNLOAD)
$(PKG_UNPACKED)
$(PKG_CONFIGURED_CONFIGURE)

$($(PKG)_BINARY): $(NZBGET_DIR)/.configured
	$(SUBMAKE) -C $(NZBGET_DIR) \
	CXXFLAGS="$(TARGET_CXXFLAGS) -fpermissive" \
	LDFLAGS="$(TARGET_LDFLAGS) $(NZBGET_LDFLAGS)" \
		LDADD="$(NZBGET_LDADD)"

$($(PKG)_TARGET_BINARY): $($(PKG)_BINARY)
	$(INSTALL_BINARY_STRIP)

$(pkg):

$(pkg)-precompiled: $($(PKG)_TARGET_BINARY)

$(pkg)-clean:
	-$(SUBMAKE) -C $(NZBGET_DIR) clean
	$(RM) $(NZBGET_DIR)/.configured

$(pkg)-uninstall:
	$(RM) $(NZBGET_TARGET_BINARY)

$(PKG_FINISH)
