YOURFRITZ_DECODER_HOST_VERSION:=bb0a8299baeab3a284979cfb189e6a469592c072
YOURFRITZ_DECODER_HOST_SOURCE:=yourfritz-decoder-$(YOURFRITZ_DECODER_HOST_VERSION).tar.xz
YOURFRITZ_DECODER_HOST_SOURCE_SHA256:=4668ad2b9433dcd0113e47490f7049573710c532b521c8add73a3c1c24c5d82b
YOURFRITZ_DECODER_HOST_SITE:=git@https://github.com/PeterPawn/decoder.git

YOURFRITZ_DECODER_HOST_MAKE_DIR:=$(TOOLS_DIR)/make/yourfritz-decoder-host
YOURFRITZ_DECODER_HOST_DIR:=$(TOOLS_SOURCE_DIR)/yourfritz-decoder-$(YOURFRITZ_DECODER_HOST_VERSION)


yourfritz-decoder-host-source: $(DL_DIR)/$(YOURFRITZ_DECODER_HOST_SOURCE)
$(DL_DIR)/$(YOURFRITZ_DECODER_HOST_SOURCE): | $(DL_DIR)
	$(DL_TOOL) $(DL_DIR) $(YOURFRITZ_DECODER_HOST_SOURCE) $(YOURFRITZ_DECODER_HOST_SITE) $(YOURFRITZ_DECODER_HOST_SOURCE_SHA256)

yourfritz-decoder-host-unpacked: $(YOURFRITZ_DECODER_HOST_DIR)/.unpacked
$(YOURFRITZ_DECODER_HOST_DIR)/.unpacked: $(DL_DIR)/$(YOURFRITZ_DECODER_HOST_SOURCE) | $(TOOLS_SOURCE_DIR) $(UNPACK_TARBALL_PREREQUISITES)
	$(call UNPACK_TARBALL,$(DL_DIR)/$(YOURFRITZ_DECODER_HOST_SOURCE),$(TOOLS_SOURCE_DIR))
	$(call APPLY_PATCHES,$(YOURFRITZ_DECODER_HOST_MAKE_DIR)/patches,$(YOURFRITZ_DECODER_HOST_DIR))
	touch $@

$(YOURFRITZ_DECODER_HOST_DIR)/.symlinked: | $(YOURFRITZ_DECODER_HOST_DIR)/.unpacked
	@ln -Tsf ../$(YOURFRITZ_DECODER_HOST_DIR:$(FREETZ_BASE_DIR)/%=%)/scripts $(TOOLS_DIR)/decoder
	touch $@

yourfritz-decoder-host-precompiled: $(YOURFRITZ_DECODER_HOST_DIR)/.symlinked


yourfritz-decoder-host-clean:

yourfritz-decoder-host-dirclean:
	$(RM) -r $(YOURFRITZ_DECODER_HOST_DIR)

yourfritz-decoder-host-distclean: yourfritz-decoder-host-dirclean
	$(RM) $(TOOLS_DIR)/decoder

