#!/bin/sh

#
# Architecture / endianness specific values
#

# Machine
ac_cv_c_littleendian=yes
ac_cv_c_bigendian=no

# Types and sizes
ac_cv_sizeof_fpos_t=20

#
# Common values for all architectures
#
. $FREETZ_BASE_DIR/include/config.site/common-linux-uclibc
