SQUASHFS4_HOST_VERSION:=4.3
SQUASHFS4_HOST_SOURCE:=squashfs$(SQUASHFS4_HOST_VERSION).tar.gz
SQUASHFS4_HOST_SOURCE_MD5:=d92ab59aabf5173f2a59089531e30dbf
SQUASHFS4_HOST_SITE:=@SF/squashfs

SQUASHFS4_HOST_MAKE_DIR:=$(TOOLS_DIR)/make/squashfs4-host
SQUASHFS4_HOST_DIR:=$(TOOLS_SOURCE_DIR)/squashfs$(SQUASHFS4_HOST_VERSION)
SQUASHFS4_HOST_BUILD_DIR:=$(SQUASHFS4_HOST_DIR)/squashfs-tools

SQUASHFS4_HOST_TOOLS:=unsquashfs
SQUASHFS4_HOST_TOOLS_BUILD_DIR:=$(addprefix $(SQUASHFS4_HOST_BUILD_DIR)/,$(SQUASHFS4_HOST_TOOLS))
SQUASHFS4_HOST_TOOLS_TARGET_DIR:=$(SQUASHFS4_HOST_TOOLS:%=$(TOOLS_DIR)/%4-lzma)

squashfs4-host-source: $(DL_DIR)/$(SQUASHFS4_HOST_SOURCE)
$(DL_DIR)/$(SQUASHFS4_HOST_SOURCE): | $(DL_DIR)
	$(DL_TOOL) $(DL_DIR) $(SQUASHFS4_HOST_SOURCE) $(SQUASHFS4_HOST_SITE) $(SQUASHFS4_HOST_SOURCE_MD5)

squashfs4-host-unpacked: $(SQUASHFS4_HOST_DIR)/.unpacked
$(SQUASHFS4_HOST_DIR)/.unpacked: $(DL_DIR)/$(SQUASHFS4_HOST_SOURCE) | $(TOOLS_SOURCE_DIR) $(UNPACK_TARBALL_PREREQUISITES)
	$(call UNPACK_TARBALL,$(DL_DIR)/$(SQUASHFS4_HOST_SOURCE),$(TOOLS_SOURCE_DIR))
	$(call APPLY_PATCHES,$(SQUASHFS4_HOST_MAKE_DIR)/patches,$(SQUASHFS4_HOST_DIR))
	touch $@

$(SQUASHFS4_HOST_TOOLS_BUILD_DIR): $(SQUASHFS4_HOST_DIR)/.unpacked $(LZMA2_DIR)/liblzma.a
	$(MAKE) -C $(SQUASHFS4_HOST_BUILD_DIR) \
		CC="$(TOOLS_CC)" \
		XZ_SUPPORT=1 \
		XZ_DIR="$(abspath $(LZMA2_DIR))" \
		GZIP_SUPPORT=1 \
		COMP_DEFAULT=xz \
		$(SQUASHFS4_HOST_TOOLS) mksquashfs
	touch -c $@

$(SQUASHFS4_HOST_TOOLS_TARGET_DIR): $(TOOLS_DIR)/%4-lzma: $(SQUASHFS4_HOST_BUILD_DIR)/%
	$(INSTALL_FILE)
	strip $@

squashfs4-host: $(SQUASHFS4_HOST_TOOLS_TARGET_DIR)

squashfs4-host-clean:
	-$(MAKE) -C $(SQUASHFS4_HOST_BUILD_DIR) clean

squashfs4-host-dirclean:
	$(RM) -r $(SQUASHFS4_HOST_DIR)

squashfs4-host-distclean: squashfs4-host-dirclean
	$(RM) $(SQUASHFS4_HOST_TOOLS_TARGET_DIR)
