$(call PKG_INIT_BIN, 1.4.0)
$(PKG)_SOURCE:=$(pkg)-$($(PKG)_VERSION).src.tar.gz
$(PKG)_SOURCE_SHA256:=015a3c2832c7c097d98a5527deef882119546287ba8f2a70c736227d764ef802
$(PKG)_SITE:=@SF/bvi

$(PKG)_BVI_BINARY:=$($(PKG)_DIR)/bvi
$(PKG)_BVI_TARGET_BINARY:=$($(PKG)_DEST_DIR)/usr/bin/bvi

$(PKG)_BMORE_BINARY:=$($(PKG)_DIR)/bmore
$(PKG)_BMORE_TARGET_BINARY:=$($(PKG)_DEST_DIR)/usr/bin/bmore

$(PKG)_BINARIES:=$($(PKG)_BVI_BINARY)
$(PKG)_TARGET_BINARIES:=$($(PKG)_BVI_TARGET_BINARY)

ifeq ($(strip $(FREETZ_PACKAGE_BVI_INCLUDE_BMORE)),y)
$(PKG)_BINARIES+=$($(PKG)_BMORE_BINARY)
$(PKG)_TARGET_BINARIES+=$($(PKG)_BMORE_TARGET_BINARY)
endif

$(PKG)_DEPENDS_ON += ncurses

$(PKG_SOURCE_DOWNLOAD)
$(PKG_UNPACKED)
$(PKG_CONFIGURED_CONFIGURE)

$($(PKG)_BVI_TARGET_BINARY): $($(PKG)_BVI_BINARY)
	$(INSTALL_BINARY_STRIP)

$($(PKG)_BMORE_TARGET_BINARY): $($(PKG)_BMORE_BINARY)
	$(INSTALL_BINARY_STRIP)

$($(PKG)_BINARIES): $($(PKG)_DIR)/.configured
	$(SUBMAKE) -C $(BVI_DIR) \
		CC="$(TARGET_CC)" \
		CFLAGS="$(TARGET_CFLAGS)"

$(pkg):

$(pkg)-precompiled: $($(PKG)_TARGET_BINARIES)

$(pkg)-clean:
	-$(SUBMAKE) -C $(BVI_DIR) clean

$(pkg)-uninstall:
	$(RM) \
		$(BVI_TARGET_BINARIES)

$(PKG_FINISH)
