#!/bin/sh

cat << EOF
domain-needed
bogus-priv
log-async=10
EOF
if [ "$DNSMASQ_DHCP" = "yes" ]; then
	echo "$DNSMASQ_DHCP_RANGE" | grep -v "^#" | while read -r range; do
		[ -n "$range" ] && echo "dhcp-range=$range"
	done
fi
[ "$DNSMASQ_ETHERS" = "yes" ] && echo "read-ethers"

isdhcphost () {
	echo $1 | grep '^dhcp-host$' >/dev/null
}
if [ -r /tmp/flash/exhosts ]; then
	egrep -v '^(#|[[:space:]]*$)' /tmp/flash/exhosts |
		while read -r ip mac interface host desc; do
			isdhcphost $mac && echo "dhcp-host=${host}"
		done
fi
