$(call PKG_INIT_BIN, 0.9.1)
$(PKG)_SOURCE:=$(pkg)-$($(PKG)_VERSION).tar.gz
$(PKG)_HASH:=a7de5a303a3784a5b6921e6a880962265b600543283c8934c5f023f631682acd
$(PKG)_SITE:=@SF/synce

$(PKG)_BINARY:=$($(PKG)_DIR)/src/dccm
$(PKG)_TARGET_BINARY:=$($(PKG)_DEST_DIR)/usr/bin/dccm

$(PKG)_DEPENDS_ON += libsynce

$(PKG)_CONFIGURE_PRE_CMDS += $(call PKG_PREVENT_RPATH_HARDCODING,./configure)

$(PKG_SOURCE_DOWNLOAD)
$(PKG_UNPACKED)
$(PKG_CONFIGURED_CONFIGURE)

$($(PKG)_BINARY): $(SYNCE_DCCM_DIR)/.configured
	$(SUBMAKE) -C $(SYNCE_DCCM_DIR)

$(SYNCE_DCCM_TARGET_BINARY): $(SYNCE_DCCM_BINARY)
	$(INSTALL_BINARY_STRIP)

$(pkg):

$(pkg)-precompiled: $($(PKG)_TARGET_BINARY)

$(pkg)-clean:
	-$(SUBMAKE) -C $(SYNCE_DCCM_DIR) clean

$(pkg)-uninstall:
	$(RM) $(SYNCE_DCCM_TARGET_BINARY)

$(PKG_FINISH)
