PACKAGE_LC:=inotify-tools
PACKAGE_UC:=INOTIFY_TOOLS
$(PACKAGE_UC)_VERSION:=3.10
$(PACKAGE_INIT_BIN)
$(PACKAGE_UC)_LIB_VERSION:=0.3.3
$(PACKAGE_UC)_SOURCE:=inotify-tools-$($(PACKAGE_UC)_VERSION).tar.gz
$(PACKAGE_UC)_SITE:=http://mesh.dl.sourceforge.net/sourceforge/inotify-tools
$(PACKAGE_UC)_INWAIT_BINARY:=$($(PACKAGE_UC)_DIR)/src/.libs/inotifywait
$(PACKAGE_UC)_INWATCH_BINARY:=$($(PACKAGE_UC)_DIR)/src/.libs/inotifywatch
$(PACKAGE_UC)_LIB_BINARY:=$($(PACKAGE_UC)_DIR)/libinotifytools/src/.libs/libinotifytools.so.$($(PACKAGE_UC)_LIB_VERSION)
$(PACKAGE_UC)_INWAIT_TARGET_BINARY:=$($(PACKAGE_UC)_DEST_DIR)/usr/bin/inotifywait
$(PACKAGE_UC)_INWATCH_TARGET_BINARY:=$($(PACKAGE_UC)_DEST_DIR)/usr/bin/inotifywatch
$(PACKAGE_UC)_LIB_TARGET_BINARY:=$($(PACKAGE_UC)_DEST_DIR)/usr/lib/libinotifytools.so.$($(PACKAGE_UC)_LIB_VERSION)

$(PACKAGE_UC)_CONFIGURE_ENV += LD="$(TARGET_LD)"


$(PACKAGE_SOURCE_DOWNLOAD)
$(PACKAGE_UNPACKED)
$(PACKAGE_CONFIGURED_CONFIGURE)

$($(PACKAGE_UC)_INWAIT_BINARY) $($(PACKAGE_UC)_TOOLS_INWATCH_BINARY) $($(PACKAGE_UC)_TOOLS_LIB_BINARY): $($(PACKAGE_UC)_TOOLS_DIR)/.configured
	PATH="$(TARGET_PATH)" $(MAKE) -C $(INOTIFY_TOOLS_DIR)
	touch $@

$($(PACKAGE_UC)_TOOLS_INWAIT_TARGET_BINARY): $($(PACKAGE_UC)_TOOLS_INWAIT_BINARY)
	$(INSTALL_BINARY_STRIP)

$($(PACKAGE_UC)_TOOLS_INWATCH_TARGET_BINARY): $($(PACKAGE_UC)_TOOLS_INWATCH_BINARY)
	$(INSTALL_BINARY_STRIP)

$($(PACKAGE_UC)_TOOLS_LIB_TARGET_BINARY): $($(PACKAGE_UC)_TOOLS_LIB_BINARY)
	mkdir -p $(dir $@)
	cp -a $(INOTIFY_TOOLS_DIR)/libinotifytools/src/.libs/libinotifytools.so* $(INOTIFY_TOOLS_TARGET_DIR)/root/usr/lib/
	$(TARGET_STRIP) $@

inotify-tools:

inotify-tools-precompiled: uclibc inotify-tools \
		$($(PACKAGE_UC)_TOOLS_INWAIT_TARGET_BINARY) \
		$($(PACKAGE_UC)_TOOLS_INWATCH_TARGET_BINARY) \
		$($(PACKAGE_UC)_TOOLS_LIB_TARGET_BINARY)

inotify-tools-clean:
	-$(MAKE) -C $(INOTIFY_TOOLS_DIR) clean
	rm -f $(INOTIFY_TOOLS_DIR)/.compiled

inotify-tools-uninstall:
	rm -f $(INOTIFY_TOOLS_INWAIT_TARGET_BINARY)
	rm -f $(INOTIFY_TOOLS_INWATCH_TARGET_BINARY)
	rm -f $(INOTIFY_TOOLS_TARGET_DIR)/root/usr/lib/libinotifytools.so*

$(PACKAGE_FINI)
