PACKAGE_LC:=inotify-tools
PACKAGE_UC:=INOTIFY_TOOLS
INOTIFY_TOOLS_VERSION:=3.10
INOTIFY_TOOLS_LIB_VERSION:=0.3.3
INOTIFY_TOOLS_SOURCE:=inotify-tools-$(INOTIFY_TOOLS_VERSION).tar.gz
INOTIFY_TOOLS_SITE:=http://mesh.dl.sourceforge.net/sourceforge/inotify-tools
INOTIFY_TOOLS_MAKE_DIR:=$(MAKE_DIR)/inotify-tools
INOTIFY_TOOLS_DIR:=$(SOURCE_DIR)/inotify-tools-$(INOTIFY_TOOLS_VERSION)
INOTIFY_TOOLS_INWAIT_BINARY:=$(INOTIFY_TOOLS_DIR)/src/.libs/inotifywait
INOTIFY_TOOLS_INWATCH_BINARY:=$(INOTIFY_TOOLS_DIR)/src/.libs/inotifywatch
INOTIFY_TOOLS_LIB_BINARY:=$(INOTIFY_TOOLS_DIR)/libinotifytools/src/.libs/libinotifytools.so.$(INOTIFY_TOOLS_LIB_VERSION)
INOTIFY_TOOLS_TARGET_DIR:=$(PACKAGES_DIR)/inotify-tools-$(INOTIFY_TOOLS_VERSION)
INOTIFY_TOOLS_INWAIT_TARGET_BINARY:=$(INOTIFY_TOOLS_TARGET_DIR)/root/usr/bin/inotifywait
INOTIFY_TOOLS_INWATCH_TARGET_BINARY:=$(INOTIFY_TOOLS_TARGET_DIR)/root/usr/bin/inotifywatch
INOTIFY_TOOLS_LIB_TARGET_BINARY:=$(INOTIFY_TOOLS_TARGET_DIR)/root/usr/lib/libinotifytools.so.$(INOTIFY_TOOLS_LIB_VERSION)
INOTIFY_TOOLS_PKG_VERSION:=0.1


$(PACKAGE_UC)_CONFIGURE_ENV += LD="$(TARGET_LD)"

$(PACKAGE_SOURCE_DOWNLOAD)
$(PACKAGE_BIN_UNPACKED)
$(PACKAGE_CONFIGURED_CONFIGURE)

$(INOTIFY_TOOLS_INWAIT_BINARY) $(INOTIFY_TOOLS_INWATCH_BINARY) $(INOTIFY_TOOLS_LIB_BINARY): $(INOTIFY_TOOLS_DIR)/.configured
	PATH="$(TARGET_PATH)" $(MAKE) -C $(INOTIFY_TOOLS_DIR)
	touch $@

$(INOTIFY_TOOLS_INWAIT_TARGET_BINARY): $(INOTIFY_TOOLS_INWAIT_BINARY)
	mkdir -p $(dir $(INOTIFY_TOOLS_TARGET_BINARY))
	$(INSTALL_BINARY_STRIP)

$(INOTIFY_TOOLS_INWATCH_TARGET_BINARY): $(INOTIFY_TOOLS_INWATCH_BINARY)
	mkdir -p $(dir $(INOTIFY_TOOLS_TARGET_BINARY))
	$(INSTALL_BINARY_STRIP)

$(INOTIFY_TOOLS_LIB_TARGET_BINARY): $(INOTIFY_TOOLS_LIB_BINARY)
	mkdir -p $(dir $(INOTIFY_TOOLS_LIB_TARGET_BINARY))
	cp -a $(INOTIFY_TOOLS_DIR)/libinotifytools/src/.libs/libinotifytools.so* $(INOTIFY_TOOLS_TARGET_DIR)/root/usr/lib/
	$(TARGET_STRIP) $@

inotify-tools:

inotify-tools-precompiled: uclibc inotify-tools \
		$(INOTIFY_TOOLS_INWAIT_TARGET_BINARY) \
		$(INOTIFY_TOOLS_INWATCH_TARGET_BINARY) \
		$(INOTIFY_TOOLS_LIB_TARGET_BINARY)

inotify-tools-source: $(INOTIFY_TOOLS_DIR)/.unpacked

inotify-tools-clean:
	-$(MAKE) -C $(INOTIFY_TOOLS_DIR) clean
	rm -f $(INOTIFY_TOOLS_DIR)/.compiled

inotify-tools-dirclean:
	rm -rf $(INOTIFY_TOOLS_DIR)
	rm -rf $(PACKAGES_DIR)/inotify-tools-$(INOTIFY_TOOLS_VERSION)

inotify-tools-uninstall:
	rm -f $(INOTIFY_TOOLS_INWAIT_TARGET_BINARY)
	rm -f $(INOTIFY_TOOLS_INWATCH_TARGET_BINARY)
	rm -f $(INOTIFY_TOOLS_TARGET_DIR)/root/usr/lib/libinotifytools.so*

$(PACKAGE_LIST)
