#!/bin/bash
# packs host-tools to dl/tools-VERSION.tar.xz in ~6min
#Arg $1: <VERSION>

VERSION="${1:-$(date '+%Y-%m-%d')}"

miniconfig() {
local i
for i in "$@"; do echo "$i=y"; done
cat << EOF
FREETZ_USER_LEVEL_EXPERT=y
# FREETZ_TOOLCHAIN_32BIT is not set
# FREETZ_TOOLCHAIN_CCACHE is not set
# FREETZ_HOSTTOOLS_DOWNLOAD is not set
FREETZ_VERBOSITY_LEVEL=0
FREETZ_DL_SITE_USER="https://github.com/Freetz-NG/dl-mirror/raw/master"
EOF
}

SKIP="kconfig"
OUTP="dl/tools-$VERSION.tar.xz"
[ -s "$OUTP" ] && echo "File $OUTP exists" && exit 1

make distclean
rm -rf dl 2>/dev/null
ln -sf ~/.freetz-dl dl
mkdir -p dl
make kconfig-host-conf
miniconfig > .config
make olddefconfig
time make tools-allexcept-local  # 5min
make tools-distclean-local
time sed -n 's,^/,tools/,p' tools/.gitignore | grep -vE "/(${SKIP// /|})$" | tar cvf - -T - | xz -9 - > "$OUTP"  # 1min
echo "################################################################"
du -h "$OUTP"
sha256sum "$OUTP" | sed 's/^/SHA256:=/;s/ .*//'
echo "OUTPUT:=${OUTP##*/}"

