#! /bin/bash
message()
{
	if [ "$1" -eq 0 ]; then
		if [ "$2" -eq 0 ]; then
			printf "Branch '%s' is even with upstream.\n" "$3"
		else
			printf "Branch '%s' is %u commits ahead of upstream.\n" "$3" $2
		fi
	else
		if [ "$2" -eq 0 ]; then
			printf "Branch '%s' is %u commits behind upstream.\n" "$3" $1
		else
			printf "Branch '%s' is %u commits behind and %u commits ahead of upstream.\n" "$3" $1 $2
		fi
	fi
}
upstream_branch="$(git rev-parse --abbrev-ref @{u} 2>/dev/null)"
[ $? -ne 0 ] && printf "Unable to get info for remote tracking branch or upstream repository.\n" && exit 1
local_branch="$(git rev-parse --abbrev-ref @)"
[ -z "$upstream_branch" ] && printf "" && exit 1
behind_count="$(git rev-list --count HEAD..${upstream_branch})"
ahead_count="$(git rev-list --count ${upstream_branch}..HEAD)"
message "$behind_count" "$ahead_count" "$local_branch" "$upstream_branch"
