#!/bin/sh

#
# converts image filename to a much shorter but still unique character sequence (i.e. suitable to be used as id)
#

cat - \
| sed -r -e 's@.*_([0-9]{4}(_?sl|_?v[1-3]|_?lte|_16|_vDSL|_v3_Edition_Italia)?|fon|fon_wlan|fon_ata|sl_wlan)([._]?(beta|labor|labbeta))?([.]Annex[AB])?(([.]en|[.]int|[.]de|[.]it)(-en|-de|-es|-it|-fr|-pl)*)?([.][0-9]{2,3}[.]0[0-9][.][0-9]{2}(-[0-9]+)?)[.]image@\1\7\9@I' \
| sed -r -e 's@[.]image$@@' \
| tr '[:upper:]' '[:lower:]'
