#! /usr/bin/perl
# Consolidate a hierarchy of kconfig menu config files (Config.in) into one big
# file

use strict;
use warnings;

sub expand {
	my $file = shift;
	print "\n# INCLUDE_BEGIN $file\n\n";

	open(my $fh, '<', $file) or die $!;
	while (<$fh>) {
	if (/^source\s+(.+)$/) {
		# For each kconfig "source" statement, recursively read sub-file
		expand($1);
	} else {
		# Print all other lines normally
		print;
	}
	}
	close($fh) or die $!;

	# Avoid kconfig "prompt redefined" warning on missing LF at EOF
	print "\n";
	print "\n# INCLUDE_END $file\n";
}

expand($_) for @ARGV;
