#!/bin/bash

generate() {

DEFAULTSET="ansi gnome konsole linux putty rxvt screen screen-w sun vt100 vt102 vt102-nsgr vt102-w vt200 vt220 vt52 xterm xterm-color xterm-256color xterm-xfree86"

cat <<"EOF"
### Do not edit this file! Run generate.sh to create it. ###


menuconfig FREETZ_SHARE_terminfo
	bool "terminfo database"
	default n

if FREETZ_SHARE_terminfo

EOF

for O in `find toolchain/target/share/terminfo -type f -o -type l | sort`; do
	DIR="$(dirname $O)"
	FILE="$(basename $O)"

	# config id
	ID="$(echo "$FILE" | sed -e 's/\./DOT/g' -e 's/-/MINUS/g' -e 's/\+/PLUS/g')"

	# check link
	if [ -L "$O" ]; then
		TARGET_O="$(basename `readlink $O`)"
		TARGET_DIR="$(dirname $TARGET_O)"
		TARGET_FILE="$(basename $TARGET_O)"

		TARGET_ID="$(echo "$TARGET_FILE" | sed -e 's/\./DOT/g' -e 's/-/MINUS/g' -e 's/\+/PLUS/g')"
	else
		TARGET_ID=""
	fi


	SIZE="$(du -b "$O" | awk '{print $1}')"
	DEFAULT="$(for I in $DEFAULTSET; do [ "$I" = "$FILE" ] && echo "y"; done)"
	[ -z "$DEFAULT" ] && DEFAULT="n"

	echo -e "\tconfig FREETZ_SHARE_terminfo_$ID"
	echo -e "\t\tbool \"$FILE ($SIZE Bytes)\""

	if [ "$DEFAULT" = "y" ]; then
		echo -e "\t\tdepends on FREETZ_SHARE_terminfo"
	else
		echo -e "\t\tdepends on FREETZ_SHARE_terminfo_showall"
	fi

	if [ -n "$TARGET_ID" ]; then
		echo -e "\t\tselect FREETZ_SHARE_terminfo_${TARGET_ID}"
	fi

	echo -e "\t\tdefault $DEFAULT"
	echo -e ""
done

cat <<"EOF"
	config FREETZ_SHARE_terminfo_showall
		bool "Show all items"
		default n
		help
			Terminfo is a library and database that enables programs to use display
			terminals in a device-independent manner. This allows external programs
			to be able to have character-based display output, independent of the
			type of terminal.

			The default selection for the Freetz should be sufficient for most
			cases. However, you can extend the selection to fit your own requirements.

endif # FREETZ_SHARE_terminfo

EOF

}

[ ! -d toolchain/target/share/terminfo ] && echo "Run 'make ncurses-precompiled' first." && exit 1
generate > make/libs/ncurses/Config.in.terminfo

