#!/bin/sh
#listen = $DNS2TCPD_LISTEN
#chroot = /tmp/dns2tcp

cat << EOF
pid_file = /var/run/dns2tcp.pid
port = $DNS2TCP_PORT
user = dns2tcp
domain = $DNS2TCP_DOMAIN
resources = $DNS2TCP_RESOURCES
EOF
