PACKAGE_LC:=capi
PACKAGE_UC:=CAPI
$(PACKAGE_UC)_VERSION:=2.0
$(PACKAGE_INIT_LIB)
$(PACKAGE_UC)_LIB_VERSION:=3.0.4
$(PACKAGE_UC)_SOURCE:=libcapi-$($(PACKAGE_UC)_VERSION).tar.bz2
$(PACKAGE_UC)_SITE:=http://dsmod.magenbrot.net
$(PACKAGE_UC)_DIR:=$(SOURCE_DIR)/libcapi-$($(PACKAGE_UC)_VERSION)
$(PACKAGE_UC)_BINARY:=$($(PACKAGE_UC)_DIR)/libcapi20.so.$($(PACKAGE_UC)_LIB_VERSION)
$(PACKAGE_UC)_STAGING_BINARY:=$(TARGET_TOOLCHAIN_STAGING_DIR)/lib/libcapi20.so.$($(PACKAGE_UC)_LIB_VERSION)
$(PACKAGE_UC)_TARGET_BINARY:=$($(PACKAGE_UC)_DEST_LIB)/libcapi20.so.$($(PACKAGE_UC)_LIB_VERSION)

$(PACKAGE_SOURCE_DOWNLOAD)
$(PACKAGE_UNPACKED)
$(PACKAGE_CONFIGURED_NOP)

$($(PACKAGE_UC)_BINARY): $($(PACKAGE_UC)_DIR)/.configured
	PATH=$(TARGET_TOOLCHAIN_PATH) \
	CROSS_COMPILE="$(TARGET_CROSS)" \
	CFLAGS="$(TARGET_CFLAGS)" \
	CAPI20_VERS="$CAPI_VERSION)" \
	$(MAKE) -C $(CAPI_DIR) all

$($(PACKAGE_UC)_STAGING_BINARY): $($(PACKAGE_UC)_BINARY)
	PATH=$(TARGET_TOOLCHAIN_PATH) $(MAKE) -C $(CAPI_DIR) \
		FILESYSTEM="$(TARGET_TOOLCHAIN_STAGING_DIR)" \
		install

$($(PACKAGE_UC)_TARGET_BINARY): $($(PACKAGE_UC)_STAGING_BINARY)
	cp -a $(TARGET_TOOLCHAIN_STAGING_DIR)/usr/lib/libcapi*.so* $(CAPI_DEST_LIB)
	$(TARGET_STRIP) $@

capi: $($(PACKAGE_UC)_STAGING_BINARY)

capi-precompiled: uclibc capi $($(PACKAGE_UC)_TARGET_BINARY)

capi-clean:
	-$(MAKE) -C $(CAPI_DIR) clean
	rm -f $(TARGET_TOOLCHAIN_STAGING_DIR)/usr/lib/libcapi20.* \
			$(STAGING_DIR)/include/capi20.h \
			$(STAGING_DIR)/include/capiutils.h \
			$(STAGING_DIR)/include/capicmd.h

capi-uninstall:
	rm -f $(CAPI_DEST_LIB_DIR)/libcapi*.so*

$(PACKAGE_FINI)
