PACKAGE_LC:=capi
PACKAGE_UC:=CAPI
$(PACKAGE_UC)_VERSION:=2.0
$(PACKAGE_INIT_LIB)
CAPI_LIB_VERSION:=3.0.4
CAPI_SOURCE:=libcapi-$(CAPI_VERSION).tar.bz2
CAPI_SITE:=http://dsmod.magenbrot.net
CAPI_DIR:=$(SOURCE_DIR)/libcapi-$($(PACKAGE_UC)_VERSION)
CAPI_BINARY:=$(CAPI_DIR)/libcapi20.so.$(CAPI_LIB_VERSION)
CAPI_STAGING_BINARY:=$(TARGET_TOOLCHAIN_STAGING_DIR)/lib/libcapi20.so.$(CAPI_LIB_VERSION)
CAPI_TARGET_BINARY:=$(CAPI_DEST_LIB)/libcapi20.so.$(CAPI_LIB_VERSION)

$(PACKAGE_SOURCE_DOWNLOAD)
$(PACKAGE_UNPACKED)
$(PACKAGE_CONFIGURED_NOP)

$($(PACKAGE_UC)_BINARY): $($(PACKAGE_UC)_DIR)/.configured
	PATH=$(TARGET_TOOLCHAIN_PATH) \
	CROSS_COMPILE="$(TARGET_CROSS)" \
	CFLAGS="$(TARGET_CFLAGS)" \
	CAPI20_VERS="$CAPI_VERSION)" \
	$(MAKE) -C $(CAPI_DIR) all

$(CAPI_STAGING_BINARY): $(CAPI_BINARY)
	PATH=$(TARGET_TOOLCHAIN_PATH) $(MAKE) -C $(CAPI_DIR) \
		FILESYSTEM="$(TARGET_TOOLCHAIN_STAGING_DIR)" \
		install

$(CAPI_TARGET_BINARY): $(CAPI_STAGING_BINARY)
	cp -a $(TARGET_TOOLCHAIN_STAGING_DIR)/usr/lib/libcapi*.so* $(CAPI_DEST_LIB)
	$(TARGET_STRIP) $@

capi: $(CAPI_STAGING_BINARY)

capi-precompiled: uclibc capi $(CAPI_TARGET_BINARY)

capi-clean:
	-$(MAKE) -C $(CAPI_DIR) clean
	rm -f $(TARGET_TOOLCHAIN_STAGING_DIR)/usr/lib/libcapi20.* \
			$(STAGING_DIR)/include/capi20.h \
			$(STAGING_DIR)/include/capiutils.h \
			$(STAGING_DIR)/include/capicmd.h

capi-uninstall:
	rm -f $(CAPI_DEST_LIB_DIR)/libcapi*.so*

$(PACKAGE_FINI)
