PACKAGE_LC:=cyassl
PACKAGE_UC:=CYASSL
$(PACKAGE_UC)_VERSION:=0.8.5
$(PACKAGE_INIT_LIB)
$(PACKAGE_UC)_SOURCE:=cyassl-$($(PACKAGE_UC)_VERSION).zip
$(PACKAGE_UC)_SITE:=http://yassl.com
$(PACKAGE_UC)_BINARY:=$($(PACKAGE_UC)_DIR)/src/.libs/libcyassl.so
$(PACKAGE_UC)_STAGING_BINARY:=$(TARGET_TOOLCHAIN_STAGING_DIR)/usr/lib/libcyassl.so
$(PACKAGE_UC)_TARGET_BINARY:=$($(PACKAGE_UC)_TARGET_DIR)/libcyassl.so

$(PACKAGE_UC)_CONFIGURE_OPTIONS += --enable-opensslExtra


$(PACKAGE_SOURCE_DOWNLOAD)
$(PACKAGE_UNPACKED)
$(PACKAGE_CONFIGURED_CONFIGURE)

$($(PACKAGE_UC)_BINARY): $($(PACKAGE_UC)_DIR)/.configured
	PATH=$(TARGET_TOOLCHAIN_PATH) \
		$(MAKE) -C $(CYASSL_DIR)

$($(PACKAGE_UC)_STAGING_BINARY): $($(PACKAGE_UC)_BINARY)
	cp -a $(CYASSL_DIR)/src/.libs/libcyassl.so* $(TARGET_TOOLCHAIN_STAGING_DIR)/usr/lib/

$($(PACKAGE_UC)_TARGET_BINARY): $($(PACKAGE_UC)_STAGING_BINARY)
	cp -a $(TARGET_TOOLCHAIN_STAGING_DIR)/usr/lib/libcyassl*.so* $(CYASSL_TARGET_DIR)/
	$(TARGET_STRIP) $@

cyassl: $($(PACKAGE_UC)_STAGING_BINARY)

cyassl-precompiled: uclibc cyassl $($(PACKAGE_UC)_TARGET_BINARY)

cyassl-clean:
	-$(MAKE) -C $(CYASSL_DIR) clean
	rm -f $(TARGET_TOOLCHAIN_STAGING_DIR)/usr/lib/libcyassl*
	rm -rf $(TARGET_TOOLCHAIN_STAGING_DIR)/usr/include/cyassl*

cyassl-uninstall:
	rm -f $(CYASSL_TARGET_DIR)/libcyassl*.so*

$(PACKAGE_FINI)
