PACKAGE_LC:=ffi-sable
PACKAGE_UC:=FFI_SABLE
$(PACKAGE_UC)_VERSION:=3325
$(PACKAGE_INIT_LIB)
$(PACKAGE_UC)_LIB_VERSION:=4.0.1
$(PACKAGE_UC)_SOURCE:=libffi-sable-$($(PACKAGE_UC)_VERSION).tar.gz
$(PACKAGE_UC)_SITE:=http://downloads.openwrt.org/sources
$(PACKAGE_UC)_DIR:=$(SOURCE_DIR)/libffi-sable-$($(PACKAGE_UC)_VERSION)
$(PACKAGE_UC)_BINARY:=$($(PACKAGE_UC)_DIR)/.libs/libffi.so.$($(PACKAGE_UC)_LIB_VERSION)
$(PACKAGE_UC)_STAGING_BINARY:=$(TARGET_TOOLCHAIN_STAGING_DIR)/usr/lib/libffi.so.$($(PACKAGE_UC)_LIB_VERSION)
$(PACKAGE_UC)_TARGET_BINARY:=$($(PACKAGE_UC)_TARGET_DIR)/libffi.so.$($(PACKAGE_UC)_LIB_VERSION)

$(PACKAGE_UC)_CONFIGURE_OPTIONS += --enable-shared
$(PACKAGE_UC)_CONFIGURE_OPTIONS += --enable-static
$(PACKAGE_UC)_CONFIGURE_OPTIONS += --disable-debug

	
$(PACKAGE_SOURCE_DOWNLOAD)
$(PACKAGE_UNPACKED)
$(PACKAGE_CONFIGURED_CONFIGURE)

$($(PACKAGE_UC)_BINARY): $($(PACKAGE_UC)_DIR)/.configured
	PATH=$(TARGET_TOOLCHAIN_PATH) \
		$(MAKE) -C $(FFI_SABLE_DIR)

$($(PACKAGE_UC)_STAGING_BINARY): $($(PACKAGE_UC)_BINARY)
	PATH=$(TARGET_TOOLCHAIN_PATH) \
		$(MAKE) -C $(FFI_SABLE_DIR) \
		DESTDIR="$(TARGET_TOOLCHAIN_STAGING_DIR)" \
		install
	$(SED) -i -e "s,^libdir=.*,libdir=\'$(TARGET_TOOLCHAIN_STAGING_DIR)/lib\',g" \
		$(TARGET_TOOLCHAIN_STAGING_DIR)/lib/libffi.la

$($(PACKAGE_UC)_TARGET_BINARY): $$(PACKAGE_UC)_STAGING_BINARY)
	cp -a $(TARGET_TOOLCHAIN_STAGING_DIR)/usr/lib/libffi*.so* $(FFI_SABLE_TARGET_DIR)/
	$(TARGET_STRIP) $@

ffi-sable: $($(PACKAGE_UC)_STAGING_BINARY)

ffi-sable-precompiled: uclibc ffi-sable $($(PACKAGE_UC)_TARGET_BINARY)

ffi-sable-clean:
	-$(MAKE) -C $(FFI_SABLE_DIR) clean
	rm -f $(TARGET_TOOLCHAIN_STAGING_DIR)/usr/lib/libffi*

ffi-sable-uninstall:
	rm -f $(FFI_SABLE_TARGET_DIR)/libffi*.so*

$(PACKAGE_FINI)
