PACKAGE_LC:=mad
PACKAGE_UC:=MAD
$(PACKAGE_UC)_VERSION:=0.15.1b
$(PACKAGE_INIT_LIB)
$(PACKAGE_UC)_LIB_VERSION:=0.2.1
$(PACKAGE_UC)_SOURCE:=libmad-$($(PACKAGE_UC)_VERSION).tar.gz
$(PACKAGE_UC)_SITE:=http://mesh.dl.sourceforge.net/sourceforge/mad
$(PACKAGE_UC)_DIR:=$(SOURCE_DIR)/libmad-$($(PACKAGE_UC)_VERSION)
$(PACKAGE_UC)_BINARY:=$($(PACKAGE_UC)_DIR)/.libs/libmad.so.$($(PACKAGE_UC)_LIB_VERSION)
$(PACKAGE_UC)_STAGING_BINARY:=$(TARGET_TOOLCHAIN_STAGING_DIR)/usr/lib/libmad.so.$($(PACKAGE_UC)_LIB_VERSION)
$(PACKAGE_UC)_TARGET_BINARY:=$($(PACKAGE_UC)_TARGET_DIR)/libmad.so.$($(PACKAGE_UC)_LIB_VERSION)

$(PACKAGE_UC)_CONFIGURE_OPTIONS += --enable-shared
$(PACKAGE_UC)_CONFIGURE_OPTIONS += --enable-static
$(PACKAGE_UC)_CONFIGURE_OPTIONS += --disable-debugging
$(PACKAGE_UC)_CONFIGURE_OPTIONS += --enable-speed
$(PACKAGE_UC)_CONFIGURE_OPTIONS += --enable-fpm="mips"


$(PACKAGE_SOURCE_DOWNLOAD)
$(PACKAGE_UNPACKED)
$(PACKAGE_CONFIGURED_CONFIGURE)

$($(PACKAGE_UC)_BINARY): $($(PACKAGE_UC)_DIR)/.configured
	PATH=$(TARGET_TOOLCHAIN_PATH) \
		$(MAKE) -C $(MAD_DIR)

$($(PACKAGE_UC)_STAGING_BINARY): $($(PACKAGE_UC)_BINARY)
	PATH=$(TARGET_TOOLCHAIN_PATH) \
		$(MAKE) -C $(MAD_DIR) \
		DESTDIR="$(TARGET_TOOLCHAIN_STAGING_DIR)" \
		install
	$(SED) -i -e "s,^libdir=.*,libdir=\'$(TARGET_TOOLCHAIN_STAGING_DIR)/lib\',g" \
		$(TARGET_TOOLCHAIN_STAGING_DIR)/lib/libmad.la

$($(PACKAGE_UC)_TARGET_BINARY): $($(PACKAGE_UC)_STAGING_BINARY)
	cp -a $(TARGET_TOOLCHAIN_STAGING_DIR)/usr/lib/libmad*.so* $(MAD_TARGET_DIR)/
	$(TARGET_STRIP) $@

mad: $($(PACKAGE_UC)_STAGING_BINARY)

mad-precompiled: uclibc mad $($(PACKAGE_UC)_TARGET_BINARY)

mad-clean:
	-$(MAKE) -C $(MAD_DIR) clean
	rm -f $(TARGET_TOOLCHAIN_STAGING_DIR)/usr/lib/libmad*

mad-uninstall:
	rm -f $(MAD_TARGET_DIR)/libmad*.so*

$(PACKAGE_FINI)