PACKAGE_LC:=readline
PACKAGE_UC:=READLINE
$(PACKAGE_UC)_VERSION:=5.2
$(PACKAGE_INIT_LIB)
$(PACKAGE_UC)_LIB_VERSION:=$($(PACKAGE_UC)_VERSION)
$(PACKAGE_UC)_SOURCE:=readline-$($(PACKAGE_UC)_VERSION).tar.gz
$(PACKAGE_UC)_SITE:=ftp://ftp.cwru.edu/pub/bash
$(PACKAGE_UC)_$(PACKAGE_UC)_BINARY:=$($(PACKAGE_UC)_DIR)/shlib/libreadline.so.$($(PACKAGE_UC)_LIB_VERSION)
$(PACKAGE_UC)_HISTORY_BINARY:=$($(PACKAGE_UC)_DIR)/shlib/libhistory.so.$($(PACKAGE_UC)_LIB_VERSION)
$(PACKAGE_UC)_STAGING_$(PACKAGE_UC)_BINARY:=$(TARGET_TOOLCHAIN_STAGING_DIR)/usr/lib/libreadline.so.$($(PACKAGE_UC)_LIB_VERSION)
$(PACKAGE_UC)_STAGING_HISTORY_BINARY:=$(TARGET_TOOLCHAIN_STAGING_DIR)/usr/lib/libhistory.so.$($(PACKAGE_UC)_LIB_VERSION)
$(PACKAGE_UC)_TARGET_$(PACKAGE_UC)_BINARY:=$($(PACKAGE_UC)_TARGET_DIR)/libreadline.so.$($(PACKAGE_UC)_LIB_VERSION)
$(PACKAGE_UC)_TARGET_HISTORY_BINARY:=$($(PACKAGE_UC)_TARGET_DIR)/libhistory.so.$($(PACKAGE_UC)_LIB_VERSION)

$(PACKAGE_UC)_CONFIGURE_ENV += bash_cv_func_sigsetjmp=yes


$(PACKAGE_SOURCE_DOWNLOAD)
$(PACKAGE_UNPACKED)
$(PACKAGE_CONFIGURED_CONFIGURE)

$($(PACKAGE_UC)_READLINE_BINARY) $($(PACKAGE_UC)_HISTORY_BINARY): $($(PACKAGE_UC)_DIR)/.configured
	PATH=$(TARGET_TOOLCHAIN_PATH) \
		$(MAKE) -C $(READLINE_DIR)

$($(PACKAGE_UC)_STAGING_READLINE_BINARY) $($(PACKAGE_UC)_STAGING_HISTORY_BINARY): \
		$($(PACKAGE_UC)_READLINE_BINARY) $($(PACKAGE_UC)_HISTORY_BINARY)
	PATH=$(TARGET_TOOLCHAIN_PATH) \
		$(MAKE) -C $(READLINE_DIR) \
		DESTDIR="$(TARGET_TOOLCHAIN_STAGING_DIR)" \
		install

$($(PACKAGE_UC)_TARGET_READLINE_BINARY): $($(PACKAGE_UC)_STAGING_READLINE_BINARY)
	chmod 755 $(TARGET_TOOLCHAIN_STAGING_DIR)/usr/lib/libreadline*.so*
	cp -a $(TARGET_TOOLCHAIN_STAGING_DIR)/usr/lib/libreadline*.so* $(READLINE_TARGET_DIR)/
	$(TARGET_STRIP) $@
	
$($(PACKAGE_UC)_TARGET_HISTORY_BINARY):  $($(PACKAGE_UC)_STAGING_HISTORY_BINARY)
	chmod 755 $(TARGET_TOOLCHAIN_STAGING_DIR)/usr/lib/libhistory*.so*
	cp -a $(TARGET_TOOLCHAIN_STAGING_DIR)/usr/lib/libhistory*.so* $(READLINE_TARGET_DIR)/
	$(TARGET_STRIP) $@

readline: $($(PACKAGE_UC)_STAGING_READLINE_BINARY) $($(PACKAGE_UC)_STAGING_HISTORY_BINARY)

readline-precompiled: uclibc ncurses-precompiled readline \
		$($(PACKAGE_UC)_TARGET_READLINE_BINARY) $($(PACKAGE_UC)_TARGET_HISTORY_BINARY)

readline-clean:
	$(MAKE) DESTDIR="$(TARGET_TOOLCHAIN_STAGING_DIR)" -C $(READLINE_DIR) uninstall
	-$(MAKE) -C $(READLINE_DIR) clean

readline-uninstall:
	rm -f $(READLINE_TARGET_DIR)/libreadline*.so*
	rm -f $(READLINE_TARGET_DIR)/libhistory*.so*

$(PACKAGE_FINI)
