PACKAGE_LC:=uclibcxx
PACKAGE_UC:=UCLIBCXX
$(PACKAGE_UC)_VERSION:=0.2.2
$(PACKAGE_INIT_LIB)
$(PACKAGE_UC)_LIB_VERSION:=$($(PACKAGE_UC)_VERSION)
$(PACKAGE_UC)_SOURCE:=uClibc++-$($(PACKAGE_UC)_VERSION).tar.bz2
$(PACKAGE_UC)_SITE:=http://cxx.uclibc.org/src/
$(PACKAGE_UC)_DIR:=$(SOURCE_DIR)/uClibc++-$($(PACKAGE_UC)_VERSION)
$(PACKAGE_UC)_BINARY:=$($(PACKAGE_UC)_DIR)/src/libuClibc++-$($(PACKAGE_UC)_LIB_VERSION).so
$(PACKAGE_UC)_STAGING_BINARY:=$(TARGET_TOOLCHAIN_STAGING_DIR)/lib/libuClibc++-$($(PACKAGE_UC)_LIB_VERSION).so
$(PACKAGE_UC)_TARGET_DIR:=root/lib
$(PACKAGE_UC)_TARGET_BINARY:=$($(PACKAGE_UC)_TARGET_DIR)/libuClibc++-$($(PACKAGE_UC)_LIB_VERSION).so

$(PACKAGE_SOURCE_DOWNLOAD)
$(PACKAGE_UNPACKED)


$($(PACKAGE_UC)_DIR)/.configured: $($(PACKAGE_UC)_DIR)/.unpacked
	cp $(UCLIBCXX_MAKE_DIR)/Config.uclibc++ $(UCLIBCXX_DIR)/.config
ifeq ($(DS_TARGET_LFS),y)
	$(SED) -i -e 's,^.*UCLIBCXX_HAS_LFS.*,UCLIBCXX_HAS_LFS=y,g' $(UCLIBCXX_DIR)/.config
else
	$(SED) -i -e 's,^.*UCLIBCXX_HAS_LFS.*,UCLIBCXX_HAS_LFS=n,g' $(UCLIBCXX_DIR)/.config
endif
	touch $@

$($(PACKAGE_UC)_BINARY): $($(PACKAGE_UC)_DIR)/.configured
	PATH=$(TARGET_TOOLCHAIN_PATH) \
		$(MAKE) -C $(UCLIBCXX_DIR) \
		ARCH_CFLAGS="$(TARGET_CFLAGS)" \
		CROSS="$(TARGET_CROSS)" \
		all

$($(PACKAGE_UC)_STAGING_BINARY): $($(PACKAGE_UC)_BINARY)
	PATH=$(TARGET_TOOLCHAIN_PATH) $(MAKE) \
		-C $(UCLIBCXX_DIR) \
		ARCH_CFLAGS="$(TARGET_CFLAGS)" \
		CROSS="$(TARGET_CROSS)" \
		DESTDIR="$(TARGET_TOOLCHAIN_STAGING_DIR)" \
		install
	mv $(TARGET_TOOLCHAIN_STAGING_DIR)/bin/g++-uc \
	   $(TARGET_TOOLCHAIN_STAGING_DIR)/bin/$(REAL_GNU_TARGET_NAME)-g++-uc
	ln -sf $(REAL_GNU_TARGET_NAME)-g++-uc $(TARGET_TOOLCHAIN_STAGING_DIR)/bin/$(GNU_TARGET_NAME)-g++-uc

$($(PACKAGE_UC)_TARGET_BINARY): $($(PACKAGE_UC)_STAGING_BINARY)
	cp -a $(TARGET_TOOLCHAIN_STAGING_DIR)/lib/libuClibc++*.so* $(UCLIBCXX_TARGET_DIR)/
	$(TARGET_STRIP) $@

uclibcxx: $($(PACKAGE_UC)_STAGING_BINARY)

uclibcxx-precompiled: uclibc uclibcxx $($(PACKAGE_UC)_TARGET_BINARY)

uclibcxx-clean:
	rm -f $(TARGET_TOOLCHAIN_STAGING_DIR)/bin/$(GNU_TARGET_NAME)-g++-uc
	rm -f $(TARGET_TOOLCHAIN_STAGING_DIR)/bin/$(REAL_GNU_TARGET_NAME)-g++-uc
	-$(MAKE) -C $(UCLIBCXX_DIR) clean
	rm -f $(TARGET_TOOLCHAIN_STAGING_DIR)/lib/libuClibc++* 

uclibcxx-uninstall:
	rm -f $(UCLIBCXX_TARGET_DIR)/libuClibc++*.so*

$(PACKAGE_FINI)