PACKAGE_LC:=usb
PACKAGE_UC:=USB
$(PACKAGE_UC)_VERSION:=0.1.12
$(PACKAGE_INIT_LIB)
$(PACKAGE_UC)_SHORT_VERSION:=0.1
$(PACKAGE_UC)_LIB_VERSION:=4.4.4
$(PACKAGE_UC)_SOURCE:=libusb-$($(PACKAGE_UC)_VERSION).tar.gz
$(PACKAGE_UC)_SITE:=http://prdownloads.sourceforge.net/libusb
$(PACKAGE_UC)_DIR:=$(SOURCE_DIR)/libusb-$($(PACKAGE_UC)_VERSION)
$(PACKAGE_UC)_BINARY:=$($(PACKAGE_UC)_DIR)/.libs/libusb-$($(PACKAGE_UC)_SHORT_VERSION).so.$($(PACKAGE_UC)_LIB_VERSION)
$(PACKAGE_UC)_STAGING_BINARY:=$(TARGET_TOOLCHAIN_STAGING_DIR)/usr/lib/libusb-$($(PACKAGE_UC)_SHORT_VERSION).so.$($(PACKAGE_UC)_LIB_VERSION)
$(PACKAGE_UC)_TARGET_BINARY:=$($(PACKAGE_UC)_TARGET_DIR)/libusb-$($(PACKAGE_UC)_SHORT_VERSION).so.$($(PACKAGE_UC)_LIB_VERSION)

$(PACKAGE_UC)_CONFIGURE_OPTIONS += --enable-shared
$(PACKAGE_UC)_CONFIGURE_OPTIONS += --enable-static


$(PACKAGE_SOURCE_DOWNLOAD)
$(PACKAGE_UNPACKED)
$(PACKAGE_CONFIGURED_CONFIGURE)

$($(PACKAGE_UC)_BINARY): $($(PACKAGE_UC)_DIR)/.configured
	PATH=$(TARGET_TOOLCHAIN_PATH) \
		$(MAKE) -C $(USB_DIR) all

$($(PACKAGE_UC)_STAGING_BINARY): $($(PACKAGE_UC)_BINARY)
	PATH=$(TARGET_TOOLCHAIN_PATH) \
		$(MAKE) -C $(USB_DIR) \
		DESTDIR="$(TARGET_TOOLCHAIN_STAGING_DIR)" \
		install
	$(SED) -i -e "s,^libdir=.*,libdir=\'$(TARGET_TOOLCHAIN_STAGING_DIR)/lib\',g" \
		$(TARGET_TOOLCHAIN_STAGING_DIR)/lib/libusb.la
	$(SED) -i -e "s,^inlcudedir=.*,includedir=\'$(TARGET_TOOLCHAIN_STAGING_DIR)/include\',g" \
		-e "s,^libdir=.*,libdir=\'$(TARGET_TOOLCHAIN_STAGING_DIR)/lib\',g" \
		$(TARGET_TOOLCHAIN_STAGING_DIR)/lib/pkgconfig/libusb.pc

$($(PACKAGE_UC)_TARGET_BINARY): $($(PACKAGE_UC)_STAGING_BINARY)
	cp -a $(TARGET_TOOLCHAIN_STAGING_DIR)/usr/lib/libusb*.so* $(USB_TARGET_DIR)/
	$(TARGET_STRIP) $@

usb: $($(PACKAGE_UC)_STAGING_BINARY)

usb-precompiled: uclibc usb $($(PACKAGE_UC)_TARGET_BINARY)

usb-clean:
	rm -f $(TARGET_TOOLCHAIN_STAGING_DIR)/bin/libusb-config
	rm -f $(TARGET_TOOLCHAIN_STAGING_DIR)/includes/usb*.h
	rm -f $(TARGET_TOOLCHAIN_STAGING_DIR)/lib/libusb*
	rm -rf $(TARGET_TOOLCHAIN_STAGING_DIR)/lib/pkgconfig
	-$(MAKE) -C $(LIBUSB_DIR) clean

usb-uninstall:
	rm -f $(USB_TARGET_DIR)/libusb*.so*

$(PACKAGE_FINI)
